// Viet lai cau luyen dich bai 18 thanh CAU GHEP co cap lien tu HSK 4.
module.exports = {
  '火|0': { prompt: 'Nhà hàng này không những làm ăn rất phát đạt, mà ngày nào trước cửa cũng xếp hàng dài.',
    answer: '这家餐厅不但生意特别火，而且每天门口都排着长队。', pair: '不但……而且……',
    note: '餐厅 là từ bài 13, 排队 là từ bài 17.' },
  '作者|0': { prompt: 'Tôi cứ tưởng tác giả cuốn tiểu thuyết này là một nhà văn lớn tuổi, ai ngờ lại là học sinh cấp hai mười mấy tuổi.',
    answer: '我本来以为这本小说的作者是个老作家，没想到竟然是个十几岁的中学生。', pair: '以为……没想到……',
    note: '作家 là từ bài 9, 竟然 là từ bài 6.' },
  '交通|0': { prompt: 'Ở đây giao thông rất thuận tiện, vì gần đây có mấy tuyến xe buýt.',
    answer: '这里交通很方便，因为附近有好几趟公共汽车。', pair: '因为……',
    note: '趟 là từ bài 17 — ở đây đếm tuyến xe.' },
  '是否|0': { prompt: 'Sách thì hay, nhưng cháu còn nhỏ thế nên tôi không biết cháu có đọc hiểu được không.',
    answer: '书虽然不错，但是她这么小，我不知道她是否能读懂。', pair: '虽然……但是……',
    note: '是否 là dạng văn viết của 是不是, không đi với 吗.' },
  '是否|1': { prompt: 'Có người chọn việc chủ yếu không phải nhìn lương, mà xem mình có thích công việc đó không.',
    answer: '有人选工作主要不是看工资，而是看自己是否喜欢这份工作。', pair: '不是……而是……',
    note: '工资 là từ bài 4, 职业 là từ bài 10.' },
  '秒|0': { prompt: 'Anh ấy chạy 100 mét chỉ mất mười một giây, nhanh hơn tôi nhiều.',
    answer: '他跑一百米只用了十一秒，比我快多了。', pair: '比……多了',
    note: '秒 → 分钟 → 小时.' },
  '方式|0': { prompt: 'Đạp xe không những là cách rèn luyện sức khoẻ rất tốt, mà còn giảm được ô nhiễm không khí.',
    answer: '骑自行车不但是一种很好的锻炼身体的方式，而且还能减少空气污染。', pair: '不但……而且……',
    note: '减少 và 污染 đều là từ bài 14.' },
  '受不了|0': { prompt: 'Tôi thật chịu không nổi bạn nữa, rốt cuộc bạn còn định dạo bao lâu?',
    answer: '我真的受不了你了，你到底还要逛多久？', pair: '到底……',
    note: '逛 là từ bài 2, 到底 là từ bài 16.' },
  '受不了|1': { prompt: 'Thầy nghiêm với các bạn là tốt, vì chỉ có như vậy các bạn mới xây được nền tảng vững.',
    answer: '他对你们严格些好，因为只有这样，你们才能打好基础。', pair: '只有……才……',
    note: '严格 là từ bài 17, 基础 là từ bài 13.' },
  '日记|0': { prompt: 'Tôi hình thành thói quen viết nhật ký mỗi ngày từ hồi tiểu học, cho nên bây giờ viết bài rất nhanh.',
    answer: '因为我从小学就养成了每天写日记的习惯，所以现在写文章很快。', pair: '因为……所以……',
    note: '养成 và 文章 đều là từ bài 11.' },
  '安全|0': { prompt: 'Có người lấy thẳng ngày sinh làm mật khẩu thẻ ngân hàng, nhưng thực ra làm vậy rất không an toàn.',
    answer: '有些人直接拿自己的生日做银行卡的密码，可是实际上这样做很不安全。', pair: '虽然……可是……',
    note: '直接 là từ bài 12, 实际上 là từ bài 5.' },
  '密码|0': { prompt: 'Tệ quá, tôi quên mật khẩu hộp thư rồi; nếu bạn biết cách lấy lại thì giúp tôi với.',
    answer: '糟糕，我把邮箱的密码忘了，要是你知道怎么找回，就帮帮我吧。', pair: '要是……就……',
    note: 'Câu chữ 把: 把 + tân ngữ + 忘了.' },
  '桥|0': { prompt: 'Chỉ cần qua cây cầu này đi tiếp khoảng 500 mét là tới ga tàu.',
    answer: '只要过了这座桥再往前走五百米左右，就是火车站。', pair: '只要……就……',
    note: '一座桥 — lượng từ 座; 左右 là từ bài 15.' },
  '接着|0': { prompt: 'Nội dung cuốn sách này rất thú vị, bạn đọc xong khoan trả, để tôi đọc tiếp.',
    answer: '这本书的内容非常有趣，你看完以后先不要还，然后我接着看。', pair: '先……然后……',
    note: '内容 là từ bài 11, 有趣 là từ bài 13.' },
  '警察|0': { prompt: 'Chính vì từ nhỏ anh ấy đã muốn bảo vệ an toàn cho mọi người, nên anh ấy chọn làm cảnh sát.',
    answer: '正因为他从小就想保护大家的安全，所以他选择了当一名警察。', pair: '因为……所以……',
    note: '保护 là từ bài 12; 一名警察 — lượng từ 名.' },
  '矿泉水|0': { prompt: 'Trời nóng quá, ra ngoài nhớ mang một chai nước suối, nếu không sẽ khát lắm.',
    answer: '天气太热，出门记得带一瓶矿泉水，不然会很渴的。', pair: '不然……',
    note: '一瓶矿泉水 — lượng từ 瓶.' },
  '付款|0': { prompt: 'Bây giờ nhiều người mua đồ đều thanh toán bằng điện thoại, cho nên không cần mang tiền mặt nữa.',
    answer: '现在很多人买东西都用手机付款，所以不用带现金了。', pair: '因为……所以……',
    note: '现金 là từ bài 5; 付款 là từ ly hợp: 付了款.' },
  '举|0': { prompt: 'Cuộc sống chúng ta đã có những thay đổi gì? Xin nêu ví dụ để nói rõ.',
    answer: '我们的生活发生了哪些变化？请举例说明。', pair: '举例……',
    note: '发生 là từ bài 8, 说明 là từ bài 7.' },
  '迷路|0': { prompt: 'Sao tôi thấy hình như chúng ta lạc đường rồi? — Không đâu, ngã tư phía trước rẽ trái là tới.',
    answer: '我怎么觉得咱们好像迷路了？——没有，只要前面路口左转，就到了。', pair: '只要……就……',
    note: '好像 là từ bài 2; 迷路 là từ ly hợp: 迷了路.' },
  '地址|0': { prompt: 'Không vấn đề gì, chỉ cần bạn cho tôi địa chỉ email là sắp xếp xong tôi gửi ngay.',
    answer: '没问题，只要把你的邮箱地址告诉我，我整理好了就发给你。', pair: '只要……就……',
    note: '整理 là từ bài 15; 地址 khác 地点.' },
  '地点|0': { prompt: 'Giờ không đổi nhưng địa điểm đổi sang cổng tây rồi, bạn mau dọn đồ đi, chúng ta xuất phát ngay.',
    answer: '时间不变，可是地点改在西门了，你快去整理一下东西吧，我们马上出发。', pair: '虽然……可是……',
    note: '地点 là nơi diễn ra sự việc; 地址 là số nhà, đường.' },
  '世纪|0': { prompt: 'Sang thế kỷ 21, cuộc sống chúng ta không những thay đổi lớn, mà còn tiện lợi hơn nhiều.',
    answer: '21世纪，我们的生活不但发生了巨大变化，而且方便多了。', pair: '不但……而且……',
    note: '变化 và 方便 quay lại từ các bài trước.' },
  '收|0': { prompt: 'Lời nói ra rồi thì rất khó thu lại, cho nên lúc giận đừng nói bừa.',
    answer: '说出去的话很难收回，因此，生气时不要随便说话。', pair: '因此……',
    note: '因此 là từ bài 8, 随便 là từ bài 9.' },
  '信封|0': { prompt: 'Hãy viết rõ địa chỉ và họ tên người nhận lên phong bì, nếu không thư sẽ không tới nơi.',
    answer: '请在信封上写清楚收信人的地址和姓名，不然信就寄不到了。', pair: '不然……',
    note: '寄 là từ bài 5; V + 不到 — không đến được.' },
  '网站|0': { prompt: 'Chỉ cần mở trang web của trường là tra được thông tin đăng ký chi tiết.',
    answer: '只要打开学校的网站，就能查到报名的详细信息。', pair: '只要……就……',
    note: '报名 là từ bài 16, 详细 là từ bài 12.' },
  '信息|0': { prompt: 'Thông tin trên Internet thật giả lẫn lộn, cho nên chúng ta phải học cách phán đoán.',
    answer: '因为互联网上的信息真真假假，所以我们要学会判断。', pair: '因为……所以……',
    note: '互联网 là từ bài 13, 判断 là từ bài 3, 假 là từ bài 15.' }
};
