// Viet lai cau luyen dich bai 14 thanh CAU GHEP co cap lien tu HSK 4.
module.exports = {
  '出差|0': { prompt: 'Thật xin lỗi, vì mai tôi phải đi công tác nên không dự họp được.',
    answer: '实在抱歉，因为明天我得出差，所以不能参加明天的会议了。', pair: '因为……所以……',
    note: '出差 là từ ly hợp: 出了三天差 ✓ / 出差了三天 ✗.' },
  '毛巾|0': { prompt: 'Vì mai tôi đi công tác, nên vợ đã cho khăn mặt, kem đánh răng và bàn chải vào vali giúp tôi.',
    answer: '因为我明天要出差，所以妻子帮我把毛巾、牙膏和牙刷都放到了箱子里。', pair: '因为……所以……',
    note: 'Câu chữ 把 với ba tân ngữ nối bằng dấu 、.' },
  '牙膏|0': { prompt: 'Kem đánh răng sắp hết rồi, mai nếu đi siêu thị thì tiện thể mua một tuýp nhé.',
    answer: '牙膏快用完了，要是明天去超市，就顺便买一支吧。', pair: '要是……就……',
    note: '顺便 là từ bài 5; 一支牙膏 — lượng từ 支.' },
  '重|0': { prompt: 'Cái vali này nặng đến mức một mình tôi không bê nổi, phiền bạn giúp một tay.',
    answer: '这个箱子重得我一个人搬不动，麻烦你帮我一下。', pair: '……得……',
    note: 'V + 不动 — bổ ngữ khả năng: không đủ sức làm.' },
  '污染|0': { prompt: 'Dùng túi nilông nhiều không những lãng phí, mà còn gây ô nhiễm môi trường nghiêm trọng.',
    answer: '塑料袋的大量使用不但很浪费，而且还带来了严重的环境污染问题。', pair: '不但……而且……',
    note: '浪费 là từ bài 5, 严重 là từ bài 7.' },
  '卫生间|0': { prompt: 'Vì hôm nay cửa hàng bận quá, nên nhà vệ sinh bẩn mà tôi cũng chưa kịp dọn.',
    answer: '因为今天店里太忙了，所以卫生间很脏，我也没来得及打扫。', pair: '因为……所以……',
    note: '来得及 là từ bài 11 — 没来得及 + V.' },
  '抱歉|0': { prompt: 'Thật sự xin lỗi, tôi đến muộn, vì hôm nay đường hơi tắc.',
    answer: '实在抱歉，我来晚了，因为今天路上有点儿堵。', pair: '因为……',
    note: '堵车 là từ bài 8; 抱歉 trang trọng hơn 对不起.' },
  '空|0': { prompt: 'Chai rỗng đừng vứt bừa, nếu thấy thùng rác thì bỏ vào đó.',
    answer: '空瓶子别乱扔，要是看到垃圾桶，就放进去吧。', pair: '要是……就……',
    note: '空 (kōng, rỗng) khác 空儿 (kòngr, thời gian rảnh — bài 10).' },
  '盒子|0': { prompt: 'Cô ấy vừa mở hộp ra là phát hiện bên trong có một chiếc khăn quàng rất đẹp.',
    answer: '她一打开盒子，就发现里面是一条漂亮的围巾。', pair: '一……就……',
    note: '一 + V + 就 + V — vừa làm việc này thì việc kia xảy ra ngay.' },
  '扔|0': { prompt: 'Được, chỉ cần anh nói một tiếng là tôi đi vứt chúng ngay.',
    answer: '好的，只要您说一声，我就马上去把它们扔掉。', pair: '只要……就……',
    note: '把 + N + 扔掉 — 掉 là bổ ngữ kết quả (bài 7).' },
  '扔|1': { prompt: 'Một trong những nguyên nhân gây ô nhiễm môi trường không phải là nhà máy, mà là có người vứt rác bừa bãi.',
    answer: '环境污染的原因之一不是工厂，而是有人乱扔垃圾。', pair: '不是……而是……',
    note: '……之一 — 之 là từ bài 11.' },
  '以|0': { prompt: 'Giám đốc cứ yên tâm, chỉ cần giao cho tôi là tôi sẽ hoàn thành với tốc độ nhanh nhất.',
    answer: '经理您放心，只要交给我，我就一定以最快的速度完成。', pair: '只要……就……',
    note: '以 + N + V — bằng, với cái gì mà làm gì.' },
  '地球|0': { prompt: 'Bảo vệ môi trường Trái đất không phải là việc xa vời khó làm, mà là việc ai cũng làm được mỗi ngày.',
    answer: '保护地球环境并不是一件离我们很远、很难做到的事情，而是每个人每天都能做的事。', pair: '不是……而是……',
    note: '并不 là từ bài 4 — phản bác điều người ta tưởng.' },
  '停|0': { prompt: 'Ở đây không được đỗ xe, nếu anh muốn đỗ thì xin đỗ vào bãi.',
    answer: '这儿不能停车，要是您想停，就请把车停到停车场去。', pair: '要是……就……',
    note: '把 + 车 + 停到 + nơi chốn + 去.' },
  '塑料袋|0': { prompt: 'Chính vì túi nilông gây ô nhiễm nghiêm trọng, nên một số nước quy định siêu thị không được phát miễn phí cho khách.',
    answer: '正因为塑料袋污染严重，所以一些国家规定，超市不能为顾客提供免费塑料袋。', pair: '因为……所以……',
    note: '规定 là từ bài 12, 提供 là từ bài 3, 顾客 là từ bài 3.' },
  '于是|0': { prompt: 'Mọi người đều đồng ý nghỉ đông đi du lịch, thế là chúng tôi bắt đầu bàn xem nên đi đâu.',
    answer: '大家都同意寒假去旅行，于是，我们开始讨论去哪里旅行的问题。', pair: '于是……',
    note: '讨论 là từ bài 13; 于是 nêu diễn biến tiếp theo, khác 所以.' },
  '拒绝|1': { prompt: 'Anh ấy đã xin công việc đó, tiếc là bị từ chối, nhưng anh ấy vẫn không bỏ cuộc.',
    answer: '他申请了那份工作，可惜被拒绝了，但是他还是没有放弃。', pair: '虽然……但是……',
    note: '申请 là từ bài 13, 可惜 là từ bài 12, 放弃 là từ bài 9.' },
  '减少|0': { prompt: 'Làm như vậy không những giảm được số lượng túi nilông, mà còn có tác dụng rất lớn với việc bảo vệ môi trường.',
    answer: '这样做不但可以减少塑料袋的使用数量，而且对环境保护有很大的作用。', pair: '不但……而且……',
    note: '作用 là từ bài 12 — 对……有作用.' },
  '温度|0': { prompt: 'Mùa hè chỉ cần để nhiệt độ điều hoà cao hơn một chút là tiết kiệm được điện.',
    answer: '夏天只要把空调的温度开得高一些，就可以节约用电。', pair: '只要……就……',
    note: '节约 là từ bài 12; 把 + 温度 + 开得 + Adj.' },
  '乘坐|0': { prompt: 'Càng ít lái xe, càng đi tàu điện và xe buýt nhiều thì ô nhiễm không khí càng giảm.',
    answer: '开车开得越少，乘坐地铁和公共汽车越多，空气污染就越低。', pair: '越……越……',
    note: '乘坐 trang trọng, hay gặp trên biển báo và thông báo.' },
  '丢|0': { prompt: 'Vì anh làm mất chìa khoá nên không vào được nhà, em mau về đi.',
    answer: '因为我的钥匙丢了，所以进不了门，你快回来吧。', pair: '因为……所以……',
    note: 'V + 不了 — không thể làm được: 进不了门.' },
  '垃圾桶|0': { prompt: 'Thùng rác lại đầy rồi, nếu anh rảnh thì đi đổ rác giúp em nhé.',
    answer: '垃圾桶又满了，要是你有空，就去扔一下垃圾吧。', pair: '要是……就……',
    note: '满 là từ bài 6, 空儿 là từ bài 10.' },
  '美丽|0': { prompt: 'Làm thế nào mới khiến Trái đất đẹp hơn? Chỉ cần mỗi người làm một chút là đủ.',
    answer: '怎样才能使地球变得更美丽？只要每个人都做一点儿，就够了。', pair: '只要……就……',
    note: '使 là từ bài 8 — 使 + N + 变得 + Adj.' }
};
