// Viet lai cau luyen dich bai 19 thanh CAU GHEP co cap lien tu HSK 4.
module.exports = {
  '学期|0': { prompt: 'Em muốn học kỳ sau tiếp tục học ở đây, vậy có cần đăng ký lại không ạ?',
    answer: '我希望下个学期在这里继续学习，那还需要重新申请吗？', pair: '既然……那……',
    note: '继续 là từ bài 13, 申请 là từ bài 13, 重新 là từ bài 2.' },
  '出生|0': { prompt: 'Không những ngày tháng năm sinh và giới tính, mà cả số hộ chiếu cũng phải điền.',
    answer: '不但出生年月、性别要填，而且护照号码也要填。', pair: '不但……而且……',
    note: '号码 là từ bài 16.' },
  '性别|0': { prompt: 'Hãy điền họ tên, giới tính, tuổi, nghề nghiệp vào mẫu đơn trước, rồi fax cho chúng tôi.',
    answer: '请先在表格上填好姓名、性别、年龄、职业等，然后再给我们传真过来。', pair: '先……然后……',
    note: '表格 và 传真 đều là từ bài 16; 等 là từ bài 10.' },
  '打印|0': { prompt: 'Vì đơn đăng ký bị người khác lấy hết rồi, nên tôi in lại cho em một bản.',
    answer: '因为申请表都被别人拿走了，所以我给你重新打印一份。', pair: '因为……所以……',
    note: '打印 là in từ máy tính; 复印 là photo bản có sẵn.' },
  '复印|0': { prompt: 'Làm visa không những cần photo hộ chiếu, mà còn cần cả bảng điểm.',
    answer: '办签证不但需要复印护照，而且还需要复印成绩证明。', pair: '不但……而且……',
    note: '签证 là từ bài 16, 证明 là từ bài 8.' },
  '饺子|0': { prompt: 'Vì tay bị đứt rồi, nên xem ra hôm nay không ăn được sủi cảo thịt dê.',
    answer: '因为手弄破了，所以看来今天吃不上羊肉饺子了。', pair: '因为……所以……',
    note: 'V + 不上 — không được hưởng, không kịp có.' },
  '刀|0': { prompt: 'Con dao này rất sắc, khi dùng nhất định phải cẩn thận, nếu không lại đứt tay.',
    answer: '这把刀很快，用的时候千万小心，不然又把手弄破了。', pair: '不然……',
    note: '千万 là từ bài 15; 快 ở đây nghĩa là "sắc".' },
  '破|0': { prompt: 'Cẩn thận một chút, nếu không lại làm vỡ cốc mất.',
    answer: '小心点儿，不然就把杯子打破了。', pair: '不然……',
    note: 'Câu chữ 把: 把 + tân ngữ + 打破.' },
  '脱|0': { prompt: 'Trên áo cũng dính chút máu, em cởi áo ra thì anh giặt cho.',
    answer: '衣服上也有一点儿血，你把衣服脱下来，我就给你洗洗。', pair: '……就……',
    note: '流血 là từ bài 7; 脱 ↔ 穿 / 戴.' },
  '理发|0': { prompt: 'Chính vì tôi làm thẻ hội viên ở tiệm cắt tóc đó, nên cắt tóc tiết kiệm được khá nhiều tiền.',
    answer: '正因为我办了一张那家理发店的会员卡，所以理发节约了不少钱。', pair: '因为……所以……',
    note: '节约 là từ bài 12; 理发 là từ ly hợp: 理了发.' },
  '包子|0': { prompt: 'Được, trong túi áo em có hơn chục đồng lẻ, chỉ cần mua bánh bao thì chắc đủ.',
    answer: '好吧，我衣服口袋里有十几块零钱，只要买包子就应该够。', pair: '只要……就……',
    note: '够 là từ bài 1; 零钱 khác 现金 (bài 5).' },
  '零钱|0': { prompt: 'Tôi trả tiền mặt, vì tiền lẻ tôi mang chắc là đủ rồi.',
    answer: '我付现金，因为我带的零钱应该够了。', pair: '因为……',
    note: '付款 là từ bài 18, 现金 là từ bài 5.' },
  '打招呼|0': { prompt: 'Sáng nay tôi chào bạn mà bạn không thấy, ai ngờ lại gặp bạn ở đây.',
    answer: '我早上跟你打招呼，你没看见，没想到又在这儿碰见你了。', pair: '以为……没想到……',
    note: '打招呼 là từ ly hợp: 打了个招呼 ✓.' },
  '戴|0': { prompt: 'Vì sáng nay tôi quên đeo kính, nên nhìn không rõ.',
    answer: '因为今天早上我忘戴眼镜了，所以看不清楚。', pair: '因为……所以……',
    note: '✗ 穿眼镜 → ✓ 戴眼镜; V + 不清楚 — không rõ.' },
  '国籍|0': { prompt: 'Lớp tôi không những có bạn từ hơn chục quốc tịch, mà ai cũng thân nhau.',
    answer: '我们班不但有来自十几个不同国籍的同学，而且大家关系都很好。', pair: '不但……而且……',
    note: '来自 là từ bài 13.' },
  '胳膊|0': { prompt: 'Vì hôm qua chơi tennis hai tiếng, nên hôm nay cánh tay đau đến không giơ nổi.',
    answer: '因为昨天打了两个小时网球，所以今天胳膊疼得抬不起来。', pair: '因为……所以……',
    note: '网球 là từ bài 9; 抬不起来 — bổ ngữ khả năng phủ định.' },
  '转|0': { prompt: 'Cô ấy vừa quay người lại là phát hiện bạn học cũ đang gọi mình.',
    answer: '她一转过身，就发现是老同学在叫她。', pair: '一……就……',
    note: '转 (zhuǎn) là quay, khác 转 (zhuàn) là xoay tròn.' },
  '租|0': { prompt: 'Một hôm anh ấy thấy tờ quảng cáo cho thuê nhà ở cổng khu chung cư, thế là gọi điện hỏi thử.',
    answer: '有一天，他在小区门口看到一个租房子的广告，于是就打电话问了问。', pair: '于是……',
    note: '广告 là từ bài 5, 于是 là từ bài 14.' },
  '吵|0': { prompt: 'Khu này ồn quá, tôi sợ ảnh hưởng đến việc học và nghỉ ngơi của con.',
    answer: '这个小区太吵了，我怕会影响孩子学习和休息。', pair: '因为……',
    note: '吵 (ồn) khác 吵架 (cãi nhau, bài 1).' },
  '厨房|0': { prompt: 'Căn hộ này không những có hai phòng ngủ và một phòng khách, mà còn có cả bếp riêng.',
    answer: '这套房子不但有两个卧室和一个客厅，而且还有一个厨房。', pair: '不但……而且……',
    note: '客厅 là từ bài 11.' },
  '房东|0': { prompt: 'Nhìn chung anh rất hài lòng với căn nhà, thế là ghi lại số điện thoại của chủ nhà.',
    answer: '总的来说，这套房子他很满意，于是他就记下了房东的手机号码。', pair: '于是……',
    note: '号码 là từ bài 16.' },
  '功夫|0': { prompt: 'Tôi biết võ Trung Quốc không những rất lợi hại, mà Kinh kịch cũng rất đặc sắc.',
    answer: '我知道中国功夫不但很厉害，而且京剧也很有特点。', pair: '不但……而且……',
    note: '京剧 là từ bài 13, 特点 là từ bài 8, 厉害 là từ bài 11.' },
  '羽毛球|0': { prompt: 'Cuối tuần chỉ cần rảnh là tôi lại cùng bạn đến nhà thi đấu chơi cầu lông.',
    answer: '周末只要有空，我就常和朋友去体育馆打羽毛球。', pair: '只要……就……',
    note: '空儿 là từ bài 10; môn dùng tay thì dùng 打.' },
  '场|0': { prompt: 'Vở Kinh kịch này tôi luôn muốn xem, mà thứ Bảy tới lại là buổi diễn cuối của họ ở đây.',
    answer: '这个京剧我一直想看，而下星期六就是他们在这儿的最后一场演出。', pair: '……，而……',
    note: '演出 là từ bài 13; 一场演出 — lượng từ 场.' },
  '座位|0': { prompt: 'Chúng tôi tất cả bốn người, phiền bạn tìm giúp một chỗ ngồi yên tĩnh hơn chút.',
    answer: '我们一共四个人，麻烦你给我们找个安静点儿的座位。', pair: '麻烦……',
    note: '麻烦 là từ bài 2 — cách nhờ vả lịch sự.' }
};
