// Viet lai cau luyen dich bai 11 thanh CAU GHEP co cap lien tu HSK 4.
module.exports = {
  '厉害|1': { prompt: 'Bác sĩ ơi, dạo này đầu tôi đau dữ dội, chẳng lẽ là do ngủ quá ít?',
    answer: '大夫，我的头最近疼得厉害，难道是因为睡得太少吗？', pair: '难道……吗？',
    note: '大夫 là từ bài 7; V + 得 + 厉害 chỉ mức độ nặng.' },
  '准确|0': { prompt: 'Vì ngữ pháp của tôi chưa tốt, nên rất nhiều câu tôi nói ra đều chưa chính xác.',
    answer: '因为我的语法确实不太好，所以我说的很多句子都不太准确。', pair: '因为……所以……',
    note: '确实 là từ bài 10; 准确 là sát chuẩn, khác 正确 (đúng/sai).' },
  '词语|0': { prompt: 'Tôi khuyên bạn kiên trì đọc báo tiếng Trung, đọc càng nhiều thì từ mới học được càng nhiều.',
    answer: '我建议你坚持看中文报纸，看得越多，学到的新词语就越多。', pair: '越……越……',
    note: '建议 là từ bài 10, 坚持 là từ bài 9.' },
  '词语|1': { prompt: 'Đứa bé không những biết gọi "bố" "mẹ", mà còn nói được vài từ đơn giản, giỏi thật.',
    answer: '孩子不但会叫"爸爸""妈妈"了，而且还能说一些简单的词语，真厉害。', pair: '不但……而且……',
    note: '真厉害 — lời khen quen thuộc trong khẩu ngữ.' },
  '阅读|0': { prompt: 'Không ngờ bạn bận thế mà vẫn kiên trì đọc sách mỗi ngày, thật giỏi.',
    answer: '我本来以为你工作那么忙就没时间了，没想到你还能每天坚持阅读，真厉害。', pair: '以为……没想到……',
    note: '阅读 trang trọng hơn 看书, dùng cho sách báo và đề thi.' },
  '复杂|0': { prompt: 'Vì đề thi đọc hiểu lần này quá nhiều câu phức tạp, nên tôi làm không kịp.',
    answer: '因为这次阅读考试的复杂题太多了，所以我来不及做完。', pair: '因为……所以……',
    note: '来不及 là từ bài 7, đối lập với 来得及 của bài này.' },
  '只好|0': { prompt: 'Vì thời gian không kịp, nên tôi đành bỏ những câu phức tạp phía sau.',
    answer: '由于时间来不及，所以我只好放弃了后面复杂的题。', pair: '由于……所以……',
    note: '由于 là từ bài 10 — chỉ đứng ở vế trước.' },
  '只好|1': { prompt: 'Vì cửa hàng đã đóng cửa, nên chúng tôi đành mai đến mua.',
    answer: '因为商店已经关门了，所以我们只好明天再来买。', pair: '因为……所以……',
    note: '只好 ≈ 不得不 (bài 4) — đều mang ý miễn cưỡng.' },
  '填空|0': { prompt: 'Vì có mấy câu điền từ tôi không làm được, nên đành đoán bừa một đáp án.',
    answer: '因为有几个填空题我不会做，所以只好随便猜了一个答案。', pair: '因为……所以……',
    note: '随便 là từ bài 9, 答案 là từ bài 10.' },
  '填空|1': { prompt: 'Mời hoàn thành các câu điền từ bên dưới; chỉ cần ngữ pháp chính xác là được điểm.',
    answer: '请完成下面的填空题，只要语法准确，就能得分。', pair: '只要……就……',
    note: '得分 — được điểm; 填空题 là dạng bài quen thuộc trong đề HSK.' },
  '猜|0': { prompt: 'Vì có mấy câu trắc nghiệm tôi nghĩ mãi không ra, nên đành đoán bừa một đáp án.',
    answer: '因为有几个选择题我想不出来该选哪个，所以就随便猜了一个答案。', pair: '因为……所以……',
    note: 'V + 不出来 — bổ ngữ khả năng phủ định: nghĩ không ra.' },
  '客厅|0': { prompt: 'Phòng khách nhà bạn sao đâu cũng là sách thế? Chẳng lẽ bạn đọc hết chỗ này rồi?',
    answer: '你的客厅里怎么到处是书啊？难道这些你都看完了吗？', pair: '难道……吗？',
    note: '到处 là từ bài 8 — 到处都是.' },
  '客厅|1': { prompt: 'Tôi vốn tưởng sô pha đặt vừa phòng khách, ai ngờ phòng lại quá nhỏ.',
    answer: '我本来以为沙发放在客厅里正好，没想到房间太小了。', pair: '以为……没想到……',
    note: '沙发 là từ bài 5, 正好 là từ bài 2.' },
  '杂志|0': { prompt: 'Tôi không những rất thích quyển tạp chí này, mà đặc biệt thích các bài về du lịch trong đó.',
    answer: '我不但对这本杂志很感兴趣，而且尤其喜欢里面关于旅游的文章。', pair: '不但……而且……',
    note: '尤其 là từ bài 5; 对 + N + 感兴趣.' },
  '杂志|1': { prompt: 'Anh ấy học từ mới bằng cách đọc tạp chí mỗi ngày, đọc càng nhiều thì nhớ càng chắc.',
    answer: '他通过每天看杂志来学习新词语，看得越多，记得就越牢。', pair: '越……越……',
    note: '通过 là từ bài 9 — 通过 + cách thức 来 + V.' },
  '增加|0': { prompt: 'Sự phát triển của khoa học tuy mang lại nhiều tiện lợi, nhưng cũng làm tăng không ít phiền muộn cho chúng ta.',
    answer: '科学的发展虽然确实带来了许多方便，但是也给我们增加了不少烦恼。', pair: '虽然……但是……',
    note: '科学 và 烦恼 là từ bài 8 và bài 7; 发展 là từ bài 10.' },
  '增加|1': { prompt: 'Thu nhập năm nay của công ty không những tăng gấp đôi so với năm ngoái, mà tiền thưởng cũng nhiều hơn.',
    answer: '公司今年的收入不但比去年增加了一倍，而且奖金也更多了。', pair: '不但……而且……',
    note: '收入 là từ bài 3, 奖金 là từ bài 4; 增加了一倍 — tăng gấp đôi.' },
  '文章|0': { prompt: 'Bài viết này không những viết khá hay, mà nội dung cũng rất phong phú, đáng để mọi người đọc thử.',
    answer: '这篇文章不仅写得挺好的，而且内容也很丰富，值得大家看一看。', pair: '不仅……而且……',
    note: '值得 là từ bài 6, 丰富 là từ bài 2.' },
  '文章|1': { prompt: 'Cứ đọc xong một bài là hãy viết ngay nội dung chính của nó ra.',
    answer: '一看完一篇文章，就把它的主要内容写下来。', pair: '一……就……',
    note: 'Câu chữ 把: 把 + tân ngữ + 写下来.' },
  '内容|0': { prompt: 'Sách quả thực dạy ta nhiều thứ, tuy nhiên bạn không thể tin hoàn toàn vào nội dung trong sách.',
    answer: '书确实能教给我们很多东西，然而你不能完全相信书本上的内容。', pair: '然而……',
    note: '然而 chỉ dùng trong văn viết, thường mở đầu câu mới.' },
  '看法|0': { prompt: 'Theo tôi thấy, quan điểm của bạn không những rất có lý, mà còn đáng để mọi người cân nhắc.',
    answer: '在我看来，你的看法不但很有道理，而且值得大家考虑。', pair: '不但……而且……',
    note: '在我看来 — theo tôi thì; 考虑 là từ bài 5.' },
  '相同|1': { prompt: 'Sở thích của hai chúng tôi tuy gần như giống hệt nhau, nhưng quan điểm lại không hoàn toàn như nhau.',
    answer: '我们俩的爱好虽然几乎完全相同，但是看法却不完全一样。', pair: '虽然……但是……',
    note: '俩 là từ bài 1; 却 là từ bài 2.' },
  '养成|0': { prompt: 'Chỉ cần tạo được thói quen đọc sách là cuộc sống của bạn sẽ phong phú hơn.',
    answer: '只要养成阅读的习惯，你的生活就会变得更丰富。', pair: '只要……就……',
    note: '养成 + … + 的习惯 — kết hợp cố định.' },
  '同时|0': { prompt: 'Anh trai tôi năm nay 26 tuổi, vừa học cao học vừa làm việc ở một công ty.',
    answer: '我哥哥今年26岁，在读硕士研究生的同时，还在一家公司工作。', pair: '在……的同时……',
    note: '硕士研究生 là từ bài 10.' },
  '同时|1': { prompt: 'Cô ấy không những là nhà khoa học nổi tiếng, mà đồng thời còn là một người mẹ tốt.',
    answer: '她不但是著名的科学家，而且同时也是一位好母亲。', pair: '不但……而且……',
    note: '母亲 là từ bài 10; 著名 trang trọng hơn 有名.' }
};
