// Viet lai cau luyen dich bai 16 thanh CAU GHEP co cap lien tu HSK 4.
module.exports = {
  '博士|0': { prompt: 'Bạn vừa có cơ hội học tiến sĩ, đồng thời cũng đỗ phỏng vấn, rốt cuộc bạn định thế nào?',
    answer: '你刚刚得到读博士的机会，同时也通过了工作面试，那你到底怎么打算的呢？', pair: '……，同时……',
    note: '同时 là từ bài 11, 通过 là từ bài 9; 到底 không đi với 吗.' },
  '签证|0': { prompt: 'Vì làm visa cần khoảng hai tuần, nên bạn phải xin trước.',
    answer: '因为办签证大概需要两个星期左右，所以你得提前申请。', pair: '因为……所以……',
    note: '左右 là từ bài 15, 提前 là từ bài 4, 申请 là từ bài 13.' },
  '报名|0': { prompt: 'Mai là ngày cuối đăng ký rồi, rốt cuộc bạn có tham gia hay không?',
    answer: '明天就是报名的最后一天了，你到底参加不参加？', pair: '到底……不……？',
    note: '报名 là từ ly hợp: 报了名 ✓ / 报名了他 ✗.' },
  '表格|0': { prompt: 'Mẫu đơn này phải điền bằng bút đen, nếu không thì họ sẽ không nhận.',
    answer: '这张表格要用黑色的笔填写，不然他们就不收了。', pair: '不然……',
    note: '一张表格 — lượng từ 张 cho vật phẳng mỏng.' },
  '传真|0': { prompt: 'Họ đã fax thư mời cho bạn chưa? Nếu chưa thì tôi gọi hỏi họ giúp.',
    answer: '他们把邀请信传真给你了吗？要是还没有，我就帮你打电话问问。', pair: '要是……就……',
    note: '邀请 là từ bài 5; 把 + N + 传真给 + ai.' },
  '参观|0': { prompt: 'Hoan nghênh đến Hải Nam xinh đẹp; mấy hôm nay sẽ do tôi dẫn mọi người tham quan.',
    answer: '欢迎来到美丽的海南，这几天就由我带着大家参观。', pair: '由……',
    note: '美丽 là từ bài 14, 由 là từ bài 13 — 由 + ai + V.' },
  '激动|0': { prompt: 'Cô ấy vừa nghe tin mình đỗ phỏng vấn là xúc động đến bật khóc.',
    answer: '她一听到自己通过了面试，就激动得哭了起来。', pair: '一……就……',
    note: '激动 + 得 + kết quả; khác 兴奋 (bài 10) là phấn khích.' },
  '代表|0': { prompt: 'Tôi thay mặt công ty cảm ơn sự ủng hộ của mọi người, vì không có mọi người thì chúng tôi không làm nổi.',
    answer: '我代表公司感谢大家的支持，因为没有大家，我们就做不到。', pair: '因为……',
    note: '感谢 là từ bài 4, 支持 là từ bài 6.' },
  '恐怕|0': { prompt: 'Vì kinh nghiệm của tôi còn ít, nên công việc đó e là tôi không hoàn thành nổi.',
    answer: '因为我的工作经验还比较少，所以那份工作我恐怕完成不了。', pair: '因为……所以……',
    note: '经验 là từ bài 4; V + 不了 — không làm nổi.' },
  '呀|0': { prompt: 'Muộn thế này rồi mà bạn còn đi đâu vậy? Chẳng lẽ có việc gấp à?',
    answer: '这么晚了，你去哪儿呀？难道有什么急事吗？', pair: '难道……吗？',
    note: '呀 là biến âm của 啊, làm câu mềm và thân mật hơn.' },
  '导游|0': { prompt: 'Hôm qua một người bạn thân gọi điện nói muốn đến du lịch, thế là nhờ tôi làm hướng dẫn viên.',
    answer: '昨天一个好朋友打电话说要来旅游，于是就让我当导游。', pair: '于是……',
    note: '于是 là từ bài 14 — nêu diễn biến tiếp theo.' },
  '挂|0': { prompt: 'Treo tấm ảnh này lên tường phòng khách đi, vì treo ở đó sẽ rất đẹp.',
    answer: '把这张照片挂在客厅的墙上吧，因为挂在那儿会很好看。', pair: '因为……',
    note: '客厅 là từ bài 11; 把 + N + 挂在 + nơi chốn + 上.' },
  '同情|0': { prompt: 'Người thích phê bình hoặc thiếu lòng thương người không những không được ai ưa, mà còn khó kết bạn.',
    answer: '爱批评人或者没有同情心的人不但最不受欢迎，而且也很难交到朋友。', pair: '不但……而且……',
    note: '批评 là từ bài 15, 交朋友 là từ bài 2.' },
  '推|0': { prompt: 'Đừng đẩy mọi việc sang "ngày mai", vì chỉ cần bắt đầu từ bây giờ là kịp.',
    answer: '不要把什么事情都推到"明天"，因为只要从现在做起，就来得及。', pair: '只要……就……',
    note: '来得及 là từ bài 11; 把 + N + 推到 + thời gian.' },
  '预习|0': { prompt: 'Đợi anh chuẩn bị xong bài rồi chơi với cháu, bà chơi trò chơi với cháu trước nhé.',
    answer: '等他预习完课文再跟你玩儿，奶奶先陪你做游戏吧。', pair: '先……再……',
    note: '陪 là từ bài 2; 预习 ↔ 复习.' },
  '自信|0': { prompt: 'Lúc phỏng vấn phải tự tin một chút, đừng ngượng, vì càng ngượng càng nói không nên lời.',
    answer: '面试的时候要自信一点儿，别害羞，因为越害羞就越说不出话。', pair: '越……越……',
    note: '害羞 là từ bài 15; V + 不出 — không thốt ra được.' },
  '敢|0': { prompt: 'Từ đó trở đi tôi không dám nằm đọc sách nữa, vì mắt càng ngày càng kém.',
    answer: '从那儿以后我就不敢再躺着看书了，因为眼睛越来越不好。', pair: '因为……',
    note: '躺 là từ bài 10; 敢 / 不敢 + V.' }
};
