// Viet lai cau luyen dich bai 7 thanh CAU GHEP co cap lien tu HSK 4.
module.exports = {
  '流血|0': { prompt: 'Mũi bạn chảy máu rồi, mau dùng giấy lau đi, nếu không sẽ bẩn hết áo.',
    answer: '你的鼻子流血了，快用纸擦擦，不然会弄脏衣服的。', pair: '不然……',
    note: '流血 là từ ly hợp: 流了很多血 ✓ / 流血了很多 ✗.' },
  '流血|1': { prompt: 'Vì vết thương này vẫn đang chảy máu, nên phải xử lý ngay.',
    answer: '因为这个伤口还在流血，所以得赶紧处理一下。', pair: '因为……所以……',
    note: '在 + V — đang diễn ra; 得 (děi) — phải.' },
  '擦|0': { prompt: 'Giám đốc bảo nhân viên phục vụ không những lau sạch hết bàn, mà còn lau cả cửa sổ nữa.',
    answer: '经理让服务员不但把所有桌子都擦干净，而且还擦了窗户。', pair: '不但……而且……',
    note: 'Câu chữ 把: 把 + tân ngữ + V + bổ ngữ kết quả 干净.' },
  '擦|1': { prompt: 'Nếu bạn rảnh thì dùng khăn lau sạch cửa sổ giúp mình nhé.',
    answer: '要是你有空，就用毛巾把窗户擦干净吧。', pair: '要是……就……',
    note: '用 + dụng cụ + 把 + tân ngữ + V — dùng gì để làm gì.' },
  '气候|0': { prompt: 'Tuy tôi ở đây đã lâu, nhưng vẫn chưa quen khí hậu miền Bắc, mùa đông lạnh quá.',
    answer: '虽然我来这儿很久了，但是还不习惯北方的气候，冬天太冷了。', pair: '虽然……但是……',
    note: '气候 là khí hậu lâu dài, khác 天气 (thời tiết hôm nay).' },
  '估计|0': { prompt: 'Nếu bạn đi hỏi thử thì tôi đoán anh ấy chắc chắn có cách.',
    answer: '如果你去问问看，我估计他一定有办法。', pair: '如果……就……',
    note: '问问看 — hỏi thử xem; 估计 dựa trên căn cứ, khác 可能.' },
  '严重|0': { prompt: 'Không sao đâu, bác sĩ nói chỉ cần uống nhiều nước là khỏi, không nghiêm trọng.',
    answer: '没事儿，大夫说只要多喝点儿水就好了，不严重。', pair: '只要……就……',
    note: '没事儿 — lời trấn an thường dùng trong khẩu ngữ.' },
  '窗户|1': { prompt: 'Vì trong phòng hơi nóng, nên bạn mở cửa sổ ra một chút đi.',
    answer: '因为房间里有点儿热，所以你把窗户打开一点儿吧。', pair: '因为……所以……',
    note: '把 + 窗户 + 打开 — câu chữ 把 với bổ ngữ xu hướng.' },
  '空气|0': { prompt: 'Vì không khí trong công viên đặc biệt trong lành, nên chúng ta ra đó đi dạo đi.',
    answer: '因为公园里的空气特别新鲜，所以我们去散散步吧。', pair: '因为……所以……',
    note: '散散步 — động từ lặp của từ ly hợp: 散 + 散 + 步.' },
  '空气|1': { prompt: 'Cứ mỗi lần trời lạnh là tôi lại thấy chưa quen khí hậu ở đây, không khí cũng khô hơn.',
    answer: '每次天一冷，我就还不习惯这里的气候，空气也更干。', pair: '一……就……',
    note: '每次……一……就…… — nhấn tính lặp lại.' },
  '动作|1': { prompt: 'Anh ấy hy vọng khi thi đấu, bất kể động tác nào cũng làm cho tốt.',
    answer: '他希望比赛的时候，不管哪个动作都要做好。', pair: '不管……都……',
    note: '不管 + 哪个 (nghi vấn phiếm chỉ)，都…… — cái nào cũng vậy.' },
  '帅|1': { prompt: 'Tôi thấy động tác này tuy trông rất ngầu, nhưng học thì không dễ.',
    answer: '我觉得这个动作虽然看上去很帅，但是学起来不容易。', pair: '虽然……但是……',
    note: 'V + 起来 — khi bắt tay vào làm thì thấy thế nào.' },
  '后悔|1': { prompt: 'Lúc đang giận thì đừng vội quyết định, nếu không sau này sẽ hối hận.',
    answer: '生气时不要急着做决定，不然以后会后悔的。', pair: '不然……',
    note: '不然 = 否则 — nếu không thì hậu quả sẽ là…' },
  '大夫|1': { prompt: 'Bạn yên tâm, bác sĩ đã nói không nghiêm trọng thì chỉ cần uống nhiều nước là khỏi.',
    answer: '你放心，既然大夫说不严重，那只要多喝点儿水就好了。', pair: '既然……就……',
    note: '既然 + sự thật đã biết，那 / 就 + kết luận.' },
  '植物|0': { prompt: 'Bác sĩ bảo tôi không những phải nhìn xa nhiều hơn, mà còn nên ngắm cây xanh nhiều hơn.',
    answer: '医生告诉我不但要多向远处看看，而且尤其要多看看绿色的植物。', pair: '不但……而且……',
    note: '尤其 là từ bài 5 — đặc biệt là.' },
  '植物|1': { prompt: 'Nhà tôi không những trồng rất nhiều cây, mà ngày nào tôi cũng tưới nước cho chúng.',
    answer: '我家不但养了很多植物，而且每天我都给它们浇水。', pair: '不但……而且……',
    note: '给 + đối tượng + 浇水 — tưới nước cho cái gì.' },
  '研究|0': { prompt: 'Nghiên cứu phát hiện, nếu ngồi yên quá lâu thì sức khỏe sẽ bị ảnh hưởng.',
    answer: '研究发现，要是长时间静坐，身体健康就会受到影响。', pair: '要是……就……',
    note: '受到影响 — 受到 là từ bài 5, mang sắc thái bị động.' },
  '研究|1': { prompt: 'Bạn tốt nghiệp xong định làm gì? Tôi thì đang cân nhắc có nên học cao học hay không.',
    answer: '你毕业后有什么打算？我既想工作，又在考虑要不要读研究生。', pair: '既……又……',
    note: '毕业 là từ bài 2, 考虑 là từ bài 5 — hai từ cũ trong một câu.' },
  '超过|1': { prompt: 'Vì tổng cộng có mười lăm người đồng ý, nên đã vượt quá hai phần ba rồi.',
    answer: '因为一共有十五个人同意，所以已经超过了三分之二。', pair: '因为……所以……',
    note: '三分之二 — phân số đọc "mẫu số 分之 tử số".' },
  '散步|0': { prompt: 'Được, chỉ cần ăn trưa xong là chúng mình ra công viên gần đây đi dạo.',
    answer: '好，只要吃完午饭，咱们就去附近的公园散散步吧。', pair: '只要……就……',
    note: '咱们 là từ bài 3 — rủ rê, gồm cả người nghe.' },
  '指|1': { prompt: 'Chữ "浪费" ở đây không phải chỉ về tiền bạc, mà là chỉ việc lãng phí thời gian.',
    answer: '"浪费"在这里不是指钱，而是指浪费时间。', pair: '不是……而是……',
    note: '浪费 là từ bài 5; A 是指 B — A ở đây nói đến B.' },
  '精神|1': { prompt: 'Cứ đi dạo xong là tinh thần tôi lại thấy khá hơn nhiều.',
    answer: '每次散完步，我的精神就感觉好多了。', pair: '一……就……',
    note: 'V + 完 — bổ ngữ kết quả chỉ việc đã xong.' },
  '教授|0': { prompt: 'Vị giáo sư đó không những dùng con số để nói rõ, mà còn kể cả chuyện của bản thân.',
    answer: '那位教授不但用数字来说明健康的重要性，而且还讲了自己的故事。', pair: '不但……而且……',
    note: '位 là lượng từ lịch sự dùng cho người đáng kính.' },
  '教授|1': { prompt: 'Chúng tôi mời một vị giáo sư đến nói về sức khỏe tinh thần, vì đây là vấn đề ngày càng nghiêm trọng.',
    answer: '我们请了一位教授来谈谈精神健康的问题，因为这个问题越来越严重。', pair: '因为……',
    note: '谈谈 — động từ lặp, nghe nhẹ nhàng hơn 谈.' },
  '数字|0': { prompt: 'Vì giáo sư dùng con số để nói rõ, nên mọi người dễ hiểu hơn nhiều.',
    answer: '因为教授用数字来说明，所以大家更容易理解。', pair: '因为……所以……',
    note: '理解 là từ bài 2 — hiểu thấu, khác 知道.' },
  '数字|1': { prompt: 'Con số này không những cho thấy vấn đề nghiêm trọng đến đâu, mà còn khiến mọi người bắt đầu chú ý.',
    answer: '这个数字不仅说明了问题有多严重，而且让大家开始注意。', pair: '不仅……而且……',
    note: '有多 + Adj — nhấn mức độ trong câu tường thuật.' },
  '说明|0': { prompt: 'Chỉ khi dùng con số để nói rõ, giáo sư mới khiến mọi người hiểu vấn đề này quan trọng đến đâu.',
    answer: '只有用数字来说明，教授才能让大家明白这个问题有多么重要。', pair: '只有……才……',
    note: '有多么 + Adj — nhấn mức độ mạnh hơn 有多.' },
  '说明|1': { prompt: 'Nếu bạn rảnh thì giải thích rõ tình hình cụ thể cho tôi nhé.',
    answer: '要是你有时间，就跟我说明一下具体的情况。', pair: '要是……就……',
    note: '情况 là từ bài 6; 说明一下 — nói rõ một chút.' },
  '减肥|1': { prompt: 'Cô ấy bơi mỗi tuần một hai lần, không phải để thi đấu, mà là để giảm cân.',
    answer: '她每周游泳一两次，目的不是为了比赛，而是为了减肥。', pair: '不是……而是……',
    note: '为了 + mục đích — 为了减肥 mà làm gì.' },
  '辛苦|0': { prompt: 'Đi dạo không những không vất vả như chạy bộ, mà ai cũng làm được.',
    answer: '散步不但不会像跑步那样辛苦，而且谁都可以做。', pair: '不但……而且……',
    note: '像……那样 — so sánh; 谁都 — ai cũng.' },
  '辛苦|1': { prompt: 'Cảm ơn bạn hôm nay đã vất vả giúp tôi, nếu không có bạn tôi đã không làm xong.',
    answer: '谢谢你今天辛苦帮我做事，要不是你，我就做不完了。', pair: '要不是……就……',
    note: '要不是 — nếu không nhờ có…; V + 不完 — làm không xong.' },
  '肚子|0': { prompt: 'Đã ăn no bụng rồi thì cần vận động, ăn xong chúng ta đi dạo một chút đi.',
    answer: '既然肚子吃饱了就需要活动，那吃完饭我们去散散步吧。', pair: '既然……就……',
    note: '活动 là từ bài 6 — ở đây là động từ "vận động".' },
  '肚子|1': { prompt: 'Bụng tôi hơi đau, có lẽ vì hôm nay ăn hơi nhiều.',
    answer: '我肚子有点儿疼，可能是因为今天吃得有点儿多。', pair: '因为……',
    note: '✗ 我疼肚子 → ✓ 我肚子疼: bộ phận cơ thể làm chủ ngữ nhỏ.' },
  '感情|0': { prompt: 'Vợ chồng ngày nào cũng cùng nhau đi dạo, vừa rèn luyện sức khỏe, vừa làm tình cảm thêm gắn bó.',
    answer: '夫妻俩每天一起散步，既能锻炼身体，又能加深感情。', pair: '既……又……',
    note: '俩 là từ bài 1 — hai người, sau 俩 không thêm lượng từ.' },
  '烦恼|1': { prompt: 'Đi dạo không những giúp người ta bớt phiền muộn trong cuộc sống, mà tinh thần cũng tốt lên.',
    answer: '散步不但可以帮助人们减少生活中的烦恼，而且精神也会好起来。', pair: '不但……而且……',
    note: 'Adj + 起来 — bắt đầu và tiếp tục tốt lên.' },
  '掉|1': { prompt: 'Bất kể bận đến đâu, bạn cũng đừng quên mất lời hứa với tôi.',
    answer: '不管多忙，你都别忘掉你对我的承诺。', pair: '不管……都……',
    note: 'V + 掉 — bổ ngữ kết quả, nhấn "mất hẳn đi".' }
};
