// Viet lai cau luyen dich bai 20 thanh CAU GHEP co cap lien tu HSK 4.
module.exports = {
  '加油站|0': { prompt: 'Đến lúc đổ xăng rồi, nếu trên đường ra sân bay có trạm xăng thì ghé vào nhé.',
    answer: '该加油了，要是去机场的路上有加油站，就顺便去一下吧。', pair: '要是……就……',
    note: '顺便 là từ bài 5; 加油站 — trạm (站) đổ xăng.' },
  '航班|0': { prompt: 'Chuyến bay vốn là 10 giờ, nhưng sau đó trang web sân bay báo hoãn một tiếng.',
    answer: '航班本来是十点的，可是后来机场网站上通知推迟了一个小时。', pair: '虽然……可是……',
    note: '本来 là từ bài 4, 网站 là từ bài 18, 通知 là từ bài 3.' },
  '高速公路|0': { prompt: 'Chỉ cần đi về phía tây 500 mét là lên được cao tốc, đi cao tốc khoảng nửa tiếng là tới.',
    answer: '只要往西走五百米，就能上高速公路，走高速公路大约半个小时就到了。', pair: '只要……就……',
    note: '大约 là từ bài 13.' },
  '首都|0': { prompt: 'Bắc Kinh không những là thủ đô Trung Quốc, mà còn là thành phố văn hoá có lịch sử mấy nghìn năm.',
    answer: '北京不但是中国的首都，而且还是一座有着几千年历史的文化名城。', pair: '不但……而且……',
    note: '一座城市 — lượng từ 座 (bài 18).' },
  '怪|0': { prompt: 'Để bạn phải chạy riêng một chuyến, thật là ngại quá.',
    answer: '让你专门跑一趟，怪不好意思的。', pair: '怪……的',
    note: '专门 là từ bài 2, 趟 là từ bài 17; 怪…的 phải đủ hai đầu.' },
  '对面|0': { prompt: 'Phố đối diện mới mở một tiệm cắt tóc, chỉ cần bạn rảnh là mình dẫn bạn qua đó.',
    answer: '对面那条街上新开了一家理发店，只要你有空，我就带你去。', pair: '只要……就……',
    note: '理发店 là từ bài 19; 对面 đứng SAU danh từ chỉ nơi chốn.' },
  '烤鸭|0': { prompt: 'Đến Bắc Kinh thì nhất định phải nếm thử vịt quay Bắc Kinh, vì đó là món nổi tiếng nhất ở đây.',
    answer: '来北京一定要尝一尝北京烤鸭，因为那是这儿最有名的小吃。', pair: '因为……',
    note: '尝 là từ bài 6; 小吃 là từ cùng bài.' },
  '祝贺|0': { prompt: 'Vất vả rồi, chúc mừng các bạn! Nào, chúng ta cạn một ly!',
    answer: '辛苦了，祝贺你们！来，咱们干一杯！', pair: '祝贺……',
    note: '辛苦 là từ bài 7, 咱们 là từ bài 3; 干杯 là từ ly hợp.' },
  '干杯|0': { prompt: 'Nào, chúng ta nâng ly vì tình bạn của mình!',
    answer: '来，为我们的友谊干杯！', pair: '为……干杯',
    note: '友谊 là từ bài 2 — 真正的友谊.' },
  '民族|0': { prompt: 'Mỗi dân tộc không những có truyền thống riêng, mà còn có văn hoá riêng của mình.',
    answer: '每个民族不但有自己的传统，而且还有自己的文化。', pair: '不但……而且……',
    note: '少数民族 — dân tộc thiểu số.' },
  '存|0': { prompt: 'Vì anh ấy muốn mua nhà, nên mỗi tháng đều gửi một phần lương vào ngân hàng.',
    answer: '因为他想买房子，所以每个月都把一部分工资存进银行。', pair: '因为……所以……',
    note: '工资 là từ bài 4, 部分 là từ bài 13; 存 ↔ 取 (bài 9).' },
  '究竟|1': { prompt: 'Rốt cuộc mùa nào đi Lệ Giang du lịch thì tốt hơn? Nếu bạn biết thì nói giúp mình.',
    answer: '究竟哪个季节去丽江旅游比较好呢？要是你知道，就告诉我一下。', pair: '要是……就……',
    note: '究竟 văn viết hơn 到底 (bài 16), cũng không đi với 吗.' },
  '汤|0': { prompt: 'Món miền Nam rất đặc sắc, nhất là canh — vị tươi ngon nên nhiều người miền Bắc cũng thích.',
    answer: '南方菜很有特点，尤其是汤，因为味道鲜美，所以很多北方人都喜欢喝。', pair: '因为……所以……',
    note: '特点 là từ bài 8, 尤其 là từ bài 5, 味道 là từ bài 5.' },
  '收拾|0': { prompt: 'Cứ về đến nhà là bạn ném quần áo sách vở lên sô pha, phòng bừa quá, tranh thủ dọn đi.',
    answer: '你一回到家就把衣服、书包什么的扔在沙发上，房间太乱了，抽时间收拾一下吧。', pair: '一……就……',
    note: '扔 là từ bài 14, 乱 là từ bài 4, 沙发 là từ bài 5.' },
  '出发|0': { prompt: 'Giờ không đổi nhưng địa điểm chuyển sang cổng tây, bạn mau dọn đồ đi, chúng ta xuất phát ngay.',
    answer: '时间不变，可是地点改在西门了，你快去收拾一下东西吧，我们马上出发。', pair: '虽然……可是……',
    note: '地点 là từ bài 18; 出发 ↔ 到达.' }
};
