// Viet lai cau luyen dich bai 17 thanh CAU GHEP co cap lien tu HSK 4.
module.exports = {
  '凉快|0': { prompt: 'Mưa xong thì mát hơn nhiều, vì mấy hôm trước thật sự quá nóng.',
    answer: '下了雨，凉快多了，因为前几天实在是太热了。', pair: '因为……',
    note: '实在 là từ bài 5; Adj + 多了 — hơn hẳn.' },
  '热闹|0': { prompt: 'Không những cổng vào rất đông người xếp hàng, mà trong sở thú cũng náo nhiệt vô cùng.',
    answer: '不但入口处排队的人很多，而且动物园里也热闹极了。', pair: '不但……而且……',
    note: 'Adj + 极了 — mức độ cao nhất.' },
  '广播|0': { prompt: 'Vừa nghe đài nói mai có thể mưa to, nên trận bóng e là phải hoãn.',
    answer: '刚才听广播说明天可能会下大雨，所以足球比赛恐怕要推迟了。', pair: '因为……所以……',
    note: '恐怕 và 推 đều là từ bài 16.' },
  '照|0': { prompt: 'Tiếc thật, vì trời mưa nên tôi không chụp thêm được ảnh Hương Sơn.',
    answer: '真可惜，因为下雨了，所以我没能多照点儿香山的照片。', pair: '因为……所以……',
    note: '可惜 là từ bài 12; 照照片 — 照 cũng dùng cho 照镜子 (bài 2).' },
  '倒|1': { prompt: 'Phiền bạn rót cho tôi cốc cà phê, vì tôi buồn ngủ chết đi được.',
    answer: '麻烦你给我倒杯咖啡吧，因为我困死了。', pair: '因为……',
    note: '困 là từ bài 10; 倒 ở đây là dào — rót, khác 倒 (lại).' },
  '抱|0': { prompt: 'Hai người bạn cũ lâu ngày không gặp, vừa thấy nhau là xúc động ôm chầm lấy nhau.',
    answer: '很久没见的两个老朋友，一见面就激动地抱在了一起。', pair: '一……就……',
    note: '激动 là từ bài 16 — 激动地 + V.' },
  '干|0': { prompt: 'Cảm ơn ngài, chỉ cần ngài tin tôi thì tôi nhất định sẽ làm cho tốt.',
    answer: '谢谢您，只要您相信我，我就一定会好好儿干的。', pair: '只要……就……',
    note: '干 (gàn) là làm, khác 干 (gān) là khô.' },
  '难受|0': { prompt: 'Ừ, ngồi lâu quả thật hơi khó chịu, chúng ta xuống đi bộ một lát đi.',
    answer: '好，坐久了确实有些难受，咱们就下去走走吧。', pair: '……就……',
    note: '确实 là từ bài 10; 难受 thiên về thân thể, 难过 thiên tâm trạng.' },
  '趟|0': { prompt: 'Vì tôi phải đi công tác một chuyến, nên nhờ bạn trông giúp con chó nhỏ được không?',
    answer: '因为我要出趟差，所以你能帮我照顾一下我的小狗吗？', pair: '因为……所以……',
    note: '出差 là từ bài 14 — 出趟差 là dạng chèn lượng từ vào từ ly hợp.' },
  '放暑假|0': { prompt: 'Sắp nghỉ hè rồi, nếu bạn chưa có kế hoạch thì cùng đi du lịch với tôi nhé.',
    answer: '马上就要放暑假了，要是你还没有安排，就跟我一起去旅行吧。', pair: '要是……就……',
    note: '安排 là từ bài 3; 马上就要……了 — sắp sửa.' },
  '老虎|0': { prompt: 'Hổ không những là một trong những loài lợi hại nhất trong rừng, mà còn chạy rất nhanh.',
    answer: '老虎不但是森林里最厉害的动物之一，而且跑得非常快。', pair: '不但……而且……',
    note: '……之一 — 之 là từ bài 11; 厉害 là từ bài 11.' },
  '入口|0': { prompt: 'Chúng ta cứ gặp nhau ở cổng vào bảo tàng lúc 10 giờ, nếu tôi đến muộn thì bạn đợi một chút nhé.',
    answer: '我们十点在博物馆的入口见面吧，要是我晚到了，你就等一会儿。', pair: '要是……就……',
    note: '入口 ↔ 出口.' },
  '活泼|0': { prompt: 'Tôi thích cô gái hoạt bát đáng yêu, chứ không phải người quá rụt rè.',
    answer: '我喜欢活泼可爱的女孩子，而不是太害羞的人。', pair: '不是……而是……',
    note: '害羞 là từ bài 15 — 活泼 ↔ 害羞.' },
  '森林|0': { prompt: 'Rừng là "lá phổi" của Trái đất, cho nên mỗi người đều có trách nhiệm bảo vệ nó.',
    answer: '因为森林是地球的"肺"，所以我们每个人都有责任保护它。', pair: '因为……所以……',
    note: '地球 là từ bài 14, 责任 là từ bài 4.' },
  '剩|0': { prompt: 'Cuốn tiểu thuyết này chỉ còn hơn chục trang, tôi muốn xem rốt cuộc kết cục thế nào.',
    answer: '这本小说就剩十几页了，我想看看到底最后怎么样。', pair: '到底……',
    note: '小说 là từ bài 6, 页 là từ bài 11, 到底 là từ bài 16.' },
  '底|0': { prompt: 'Chìa khoá có lẽ rơi xuống gầm sô pha rồi, nếu bạn rảnh thì tìm giúp mình nhé.',
    answer: '钥匙可能掉到沙发底下了，要是你有空，就帮我找找看。', pair: '要是……就……',
    note: '掉 là từ bài 7, 沙发 là từ bài 5.' },
  '美人鱼|0': { prompt: '"Nàng tiên cá" không những là truyện cổ tích nổi tiếng của Andersen, mà còn được dịch sang rất nhiều thứ tiếng.',
    answer: '《美人鱼》不但是安徒生写的一个著名的童话故事，而且还被翻译成了很多种语言。', pair: '不但……而且……',
    note: '著名 là từ bài 11, 翻译 là từ bài 10, 语言 là từ bài 12.' },
  '公里|0': { prompt: 'Nhà tôi cách công ty khoảng năm cây số, chỉ cần đạp xe hai mươi phút là tới.',
    answer: '我家离公司大约五公里，只要骑车二十分钟左右就到。', pair: '只要……就……',
    note: '大约 là từ bài 13, 左右 là từ bài 15.' },
  '仍然|0': { prompt: 'Người tuy thông minh hơn động vật, nhưng động vật vẫn có nhiều điểm đáng để người học.',
    answer: '人虽然比动物聪明，但是动物仍然有很多值得人学习的地方。', pair: '虽然……但是……',
    note: '值得 là từ bài 6; 仍然 thiên văn viết hơn 还是.' }
};
