// Viet lai cau luyen dich bai 6 thanh CAU GHEP co cap lien tu HSK 4.
module.exports = {
  '果汁|1': { prompt: 'Đã chỉ mua chút đồ thế này thì làm gì mất nhiều thời gian đến vậy!',
    answer: '既然只买这么点儿东西，就用不了那么长时间啊！', pair: '既然……就……',
    note: 'V + 不了 — bổ ngữ khả năng phủ định: không thể, không hết.' },
  '售货员|0': { prompt: 'Chúng tôi vừa vào trung tâm mua sắm là nhân viên bán hàng liền nhiệt tình giới thiệu cái này cái kia.',
    answer: '我们一去商场，售货员就热情地为我们介绍这、介绍那。', pair: '一……就……',
    note: '为 + ai + V — làm gì cho ai; 地 đứng sau tính từ làm trạng ngữ.' },
  '售货员|1': { prompt: 'Khi mua đồ tôi không những chỉ xem cái mình muốn mua, mà còn không muốn bị nhân viên làm phiền.',
    answer: '买东西时我不但只看自己想买的，而且不希望被售货员打扰。', pair: '不但……而且……',
    note: '被 + ai + V — câu bị động, thường mang sắc thái không mong muốn.' },
  '袜子|1': { prompt: 'Chỉ cần hôm nay mua đủ 400 tệ, mua thêm hai đôi tất nữa là đủ.',
    answer: '只要今天购物满四百元，再买两双袜子就够了。', pair: '只要……就……',
    note: '满 + số tiền — mua đủ bao nhiêu; 双 là lượng từ cho vật đi đôi.' },
  '打扰|0': { prompt: 'Khi mua đồ tôi không những thích tự xem tự chọn, mà còn không muốn bị người khác làm phiền.',
    answer: '买东西时我不但喜欢自己看、自己选，而且不希望被别人打扰。', pair: '不但……而且……',
    note: '自己 + V — tự mình làm gì.' },
  '打扰|1': { prompt: 'Nếu không làm phiền bạn thì tôi hỏi một chút, được không?',
    answer: '如果不打扰你的话，我就问一下，好吗？', pair: '如果……就……',
    note: '……的话 hay đi cùng 如果 / 要是 để nhấn ý giả thiết.' },
  '竟然|0': { prompt: 'Tuy tiếng Thượng Hải và tiếng Bắc Kinh gần như hoàn toàn khác nhau, nhưng bạn lại nghe hiểu được cơ à?',
    answer: '虽然上海话和北京话几乎完全不同，但是你竟然听得懂？', pair: '虽然……但是……',
    note: '听得懂 — bổ ngữ khả năng khẳng định, phủ định là 听不懂.' },
  '竟然|1': { prompt: 'Mặc dù đường xa như vậy, bạn vẫn đạp xe đến thật à?',
    answer: '尽管路这么远，你竟然还是骑自行车来了？', pair: '尽管……还是……',
    note: '竟然 nêu điều nằm ngoài dự đoán, hơi ngạc nhiên.' },
  '西红柿|0': { prompt: 'Nếu cà chua này tươi thì tôi mua hai cân, bao nhiêu tiền một cân vậy?',
    answer: '如果这西红柿新鲜，我就买两斤，多少钱一斤？', pair: '如果……就……',
    note: '斤 = 500 gam, đơn vị cân quen thuộc ở Trung Quốc.' },
  '西红柿|1': { prompt: 'Chỉ cần mỗi ngày ăn một hai quả cà chua tươi là có lợi cho da.',
    answer: '只要每天吃一两个新鲜的西红柿，就对皮肤有好处。', pair: '只要……就……',
    note: '一两个 — khoảng một hai cái, hai số liền nhau chỉ ước lượng.' },
  '百分之|0': { prompt: 'Chúng tôi không những cam đoan hàng tươi 100%, mà không ngon còn được trả lại, chị cứ yên tâm mua.',
    answer: '我们不但保证质量百分之百新鲜，而且不好可以退，您放心买吧。', pair: '不但……而且……',
    note: '保证 là từ bài 4; 百分之百 = hoàn toàn.' },
  '百分之|1': { prompt: 'Trong số khách hàng chúng tôi khảo sát, tuy có 60% thấy giá hợp lý, nhưng vẫn còn 40% thấy quá đắt.',
    answer: '我们调查的顾客中，虽然有百分之六十的人觉得价格合理，但是还有百分之四十觉得太贵。', pair: '虽然……但是……',
    note: '调查 là từ bài 4, 顾客 là từ bài 3 — ôn lại cùng lúc.' },
  '倍|0': { prompt: '200 không phải gấp ba lần 100, mà là gấp hai lần.',
    answer: '200不是100的三倍，而是两倍。', pair: '不是……而是……',
    note: 'A 是 B 的 + số + 倍 — chỗ học sinh Việt hay nhầm 一倍 với 两倍.' },
  '倍|1': { prompt: 'Tôi cứ tưởng vẫn ba tệ rưỡi một cân như hôm qua, ai ngờ giá hôm nay lại gấp đôi hôm qua.',
    answer: '我本来以为跟昨天一样是三块五一斤，没想到今天的价格竟然是昨天的两倍。', pair: '以为……没想到……',
    note: '以为 là nghĩ SAI — vế sau bắt buộc trái với điều đã nghĩ.' },
  '皮肤|0': { prompt: 'Ăn loại cà chua tươi này mỗi ngày không những rất tốt cho da, mà còn tốt cho cơ thể.',
    answer: '每天吃这种新鲜的西红柿，不但对皮肤很有好处，而且对身体也好。', pair: '不但……而且……',
    note: '对 + N + 有好处 — kết hợp cố định.' },
  '皮肤|1': { prompt: 'Vì bây giờ trời lạnh, nên phải chú ý bảo vệ da.',
    answer: '因为现在天气冷，所以要注意保护皮肤。', pair: '因为……所以……',
    note: '注意 + V — chú ý làm gì.' },
  '好处|1': { prompt: 'Tích lũy kinh nghiệm làm việc không những có lợi cho hiện tại, mà lợi ích cho tương lai còn nhiều hơn.',
    answer: '积累工作经验不但对现在有好处，而且对未来的好处更多。', pair: '不但……而且……',
    note: '积累经验 là từ bài 4 — quay lại ở ngữ cảnh mới.' },
  '尝|0': { prompt: 'Loại cà chua này đã tươi như vậy thì chị mua vài quả nếm thử trước đi.',
    answer: '既然这种西红柿很新鲜，您就先买几个尝尝吧。', pair: '既然……就……',
    note: '尝尝 — động từ lặp, làm câu nhẹ và lịch sự hơn.' },
  '尝|1': { prompt: 'Bạn nếm thử món này trước, rồi nói cho tôi biết có ngon không.',
    answer: '你先尝尝这道菜，然后告诉我好不好吃。', pair: '先……然后……',
    note: '好不好吃 — dạng hỏi chính phản làm tân ngữ.' },
  '轻|0': { prompt: 'Vì bên trong có đồ dễ vỡ, nên phiền anh khiêng chiếc vali này nhẹ tay một chút.',
    answer: '因为里面有易碎的东西，所以麻烦您搬这个行李箱的时候轻一点儿。', pair: '因为……所以……',
    note: '麻烦您 + V — cách nhờ vả lịch sự, học ở bài 2.' },
  '方面|1': { prompt: 'Bản kế hoạch bạn xem chưa? Không những mọi mặt đều giới thiệu khá tốt, mà nội dung cũng rất phong phú.',
    answer: '计划书你看了没？不仅各方面都介绍得挺不错，而且内容也很丰富。', pair: '不仅……而且……',
    note: '丰富 là từ bài 2; 各方面 — mọi phương diện.' },
  '值得|0': { prompt: 'Chiếc sô pha này không những giá không đắt, mà chất lượng lại tốt, thật đáng mua.',
    answer: '这个沙发不但价钱不贵，而且质量又好，真值得买。', pair: '不但……而且……',
    note: 'Sau 值得 phải là động từ: 值得买 ✓ / 值得很好 ✗.' },
  '活动|0': { prompt: 'Vì hiệu sách chúng tôi đang đúng đợt "mua sách tặng quà", nên mua sách bây giờ rẻ hơn ngày thường.',
    answer: '因为现在我们书店正好有"购书送好礼"活动，所以现在买书比平时便宜。', pair: '因为……所以……',
    note: '正好 là từ bài 2, 平时 cũng vậy — hai từ cũ trong một câu.' },
  '内|1': { prompt: 'Chỉ cần hôm nay anh mua là chúng tôi sẽ giao hàng trong vòng ba ngày.',
    answer: '只要您今天买，我们就会在三日内把东西送到。', pair: '只要……就……',
    note: '在 + thời lượng + 内 — trong vòng bao lâu; 内 luôn đứng sau.' },
  '免费|1': { prompt: 'Nếu bây giờ mua tủ lạnh thì có được giao hàng tận nhà miễn phí không?',
    answer: '要是现在买冰箱，是不是就能免费送货上门？', pair: '要是……就……',
    note: '要是 = 如果, thiên khẩu ngữ hơn.' },
  '修理|0': { prompt: 'Chiếc vali này không những chất lượng tốt, mà trong vòng một năm cửa hàng còn sửa miễn phí.',
    answer: '这个行李箱不但质量不错，而且一年内店里还负责免费修理。', pair: '不但……而且……',
    note: '负责 là từ bài 3 — chịu trách nhiệm việc gì.' },
  '修理|1': { prompt: 'Vì tủ lạnh nhà mình hỏng rồi, nên phải tìm thợ đến sửa.',
    answer: '因为咱家的冰箱坏了，所以得找师傅来修理。', pair: '因为……所以……',
    note: '咱 là dạng rút gọn của 咱们 (bài 3); 得 ở đây đọc là děi — phải.' },
  '支持|0': { prompt: 'Cảm ơn sự ủng hộ và giúp đỡ của mọi người suốt một năm qua; chỉ khi làm việc cùng mọi người tôi mới làm được thuận lợi như vậy.',
    answer: '谢谢大家这一年来对我的支持和帮助，只有跟大家一起工作，我才能做得这么顺利。', pair: '只有……才……',
    note: '顺利 là từ bài 4 — xuất hiện lại ở lời cảm ơn.' },
  '小说|0': { prompt: 'Trong số sách đang giảm giá, vì tiểu thuyết giảm còn 75% nên tôi muốn mua thêm vài cuốn.',
    answer: '在打折的图书中，因为小说打7.5折，所以我想多买几本。', pair: '因为……所以……',
    note: '打7.5折 = còn 75% giá, tức giảm 25% — ngược cách nói tiếng Việt.' },
  '小说|1': { prompt: 'Quyển tiểu thuyết này không những kể một chuyện tình rất cảm động, mà còn viết rất hay.',
    answer: '这本小说不仅讲了一个很感人的爱情故事，而且写得特别好。', pair: '不仅……而且……',
    note: '爱情 là từ bài 1; 本 là lượng từ cho sách.' },
  '所有|0': { prompt: 'Bất kể là bạn nào sinh nhật hôm nay hay tất cả các bạn nhỏ, đều được nhận miễn phí một món quà nhỏ.',
    answer: '不管是今天过生日的朋友，还是所有的小朋友，都可以免费获得一份小礼物。', pair: '不管是……还是……',
    note: '不管是 A 还是 B，都…… — hai khả năng, kết quả như nhau.' },
  '所有|1': { prompt: 'Chỉ cần là trẻ nhỏ thì tất cả mọi người đều nên đối xử tốt với các em.',
    answer: '只要是小朋友，所有人都应该对他们好。', pair: '只要……都……',
    note: '对 + ai + 好 — đối xử tốt với ai.' },
  '获得|0': { prompt: 'Chỉ cần hôm nay mua sắm đủ 400 tệ là khách hàng được nhận miễn phí một món quà nhỏ.',
    answer: '只要今天购物满四百元，顾客就可以免费获得一份小礼物。', pair: '只要……就……',
    note: '购物 là từ bài 5, 顾客 là từ bài 3.' },
  '举办|1': { prompt: 'Trường sắp tổ chức một hoạt động, không những rất có ý nghĩa mà tất cả các bạn đều tham gia được.',
    answer: '学校马上要举办一个活动，不但很有意义，而且所有同学都能参加。', pair: '不但……而且……',
    note: '举办 nhấn người đứng ra tổ chức; 举行 nhấn sự việc diễn ra.' },
  '各|1': { prompt: 'Tôi xem kế hoạch rồi, không những mọi mặt đều giới thiệu khá tốt, mà còn viết rất rõ ràng.',
    answer: '我看了计划，不仅各方面都介绍得挺不错，而且写得很清楚。', pair: '不仅……而且……',
    note: 'Sau 各 không dùng 的: 各方面 ✓ / 各的方面 ✗.' }
};
