// Viet lai cau luyen dich bai 9 thanh CAU GHEP co cap lien tu HSK 4.
module.exports = {
  '饼干|1': { prompt: 'Số bánh quy này tôi mua cho con, nếu bạn ăn hết thì lát nữa con tôi lại khóc đấy.',
    answer: '这些饼干是我给孩子买的，要是你都吃了，一会儿他就该哭了。', pair: '要是……就……',
    note: '该……了 — sắp phải, sắp xảy ra rồi.' },
  '得|1': { prompt: 'Vì tôi phải đến đại sứ quán trước 9 giờ, nên phiền bác đi nhanh hơn một chút.',
    answer: '因为我得在九点之前到大使馆，所以麻烦您快点儿。', pair: '因为……所以……',
    note: '得 ở đây đọc děi — phải; phủ định là 不用 chứ không phải 不得.' },
  '放弃|0': { prompt: 'Nghe nói sau khi tốt nghiệp cô ấy đã bỏ nghề luật sư để chuyên viết tiểu thuyết, cứ tưởng khó thành, ai ngờ lại thành công.',
    answer: '听说她毕业后放弃了律师的工作，专门写小说，本来以为很难成功，没想到真的成功了。', pair: '以为……没想到……',
    note: '律师 (bài 3), 专门 (bài 2), 小说 (bài 6) cùng xuất hiện lại.' },
  '主意|0': { prompt: 'Chính vì lời bạn nói vừa rồi mà tôi đổi ý, nên tôi quyết định không bỏ cuộc nữa.',
    answer: '正因为你刚才的话让我改变了主意，所以我决定不放弃了。', pair: '因为……所以……',
    note: '改变 là từ bài 3 — 改变主意 là kết hợp cố định.' },
  '主意|1': { prompt: 'Việc này tôi cũng chưa biết làm sao, nếu bạn rảnh thì giúp tôi nghĩ một ý hay nhé.',
    answer: '这件事我也不知道该怎么办，要是你有空，就帮我想个好主意吧。', pair: '要是……就……',
    note: '该怎么办 — nên làm thế nào đây.' },
  '网球|0': { prompt: 'Bạn đánh quần vợt giỏi thật, tuy mỗi lần xem tôi đều thấy bạn thắng nhẹ tênh, nhưng thật ra bạn luyện rất vất vả.',
    answer: '你网球打得真好，虽然每次看你比赛都感觉你轻轻松松就赢了，但是其实你练得很辛苦。', pair: '虽然……但是……',
    note: '辛苦 là từ bài 7; 打得真好 — lặp động từ để mang bổ ngữ.' },
  '轻松|0': { prompt: 'Sở dĩ mỗi lần xem bạn thi đấu tôi đều thấy bạn thắng nhẹ tênh, là vì bạn đã luyện tập rất vất vả.',
    answer: '因为你平时练习得很辛苦，所以每次比赛才看起来轻轻松松就赢了。', pair: '因为……所以……',
    note: '平时 là từ bài 2; 看起来 — nhìn thì có vẻ.' },
  '随便|1': { prompt: 'Việc quan trọng thế này, dù bận đến mấy bạn cũng không thể quyết định qua loa.',
    answer: '这么重要的事，不管多忙，你都不能随便决定。', pair: '不管……都……',
    note: '不管 + 多 + Adj，都…… — dù thế nào cũng vậy.' },
  '通过|1': { prompt: 'Tôi hy vọng không những khơi được hứng thú của mọi người qua hoạt động lần này, mà còn để mọi người hiểu công ty hơn.',
    answer: '我希望通过这次活动不但能引起大家的兴趣，而且还能让大家更了解我们公司。', pair: '不但……而且……',
    note: '通过 + N — nhờ vào cái gì; 活动 là từ bài 6.' },
  '篇|0': { prompt: 'Tôi đọc được một bài báo về cô ấy, mới biết hóa ra cô ấy đã là nhà văn nổi tiếng.',
    answer: '我一在报纸上看到一篇关于她的新闻，就知道她现在已经是一个有名的作家了。', pair: '一……就……',
    note: '关于 + N + 的 + N — bài viết về cái gì.' },
  '篇|1': { prompt: 'Bài viết này không những kể về trải nghiệm thành công của cô ấy, mà còn kể cả những thất bại cô ấy từng gặp.',
    answer: '这篇文章不仅写了她的成功经历，而且还写了她经历过的失败。', pair: '不仅……而且……',
    note: '篇 dùng cho bài viết, 本 dùng cho sách.' },
  '作家|1': { prompt: 'Anh ấy mơ làm nhà văn từ nhỏ, và chính vì kiên trì nên bây giờ ước mơ đã thành hiện thực.',
    answer: '他从小就梦想成为一名作家，正因为一直坚持，所以现在这个梦想终于实现了。', pair: '因为……所以……',
    note: '名 là lượng từ lịch sự cho người có nghề nghiệp.' },
  '正确|0': { prompt: 'Chỉ sau khi thành công, cô ấy mới chứng minh được với mọi người rằng lựa chọn của mình là đúng đắn.',
    answer: '只有成功以后，她才向大家证明了自己的选择是正确的。', pair: '只有……才……',
    note: '证明 là từ bài 8 — 向 + ai + 证明.' },
  '理想|1': { prompt: 'Bạn thi cao học thế nào? Nếu kết quả không được như ý thì sang năm thi lại cũng được mà.',
    answer: '你研究生考试考得怎么样？要是结果不太理想，就明年再考一次吧。', pair: '要是……就……',
    note: '研究生 là từ bài 7; 理想 ở đây là tính từ "như ý".' },
  '失败|0': { prompt: 'Đừng lo kết quả, cũng đừng nghĩ có thất bại hay không; chỉ cần dũng cảm làm là được.',
    answer: '不要担心结果，也不要考虑会不会失败，只要勇敢地去做就行。', pair: '只要……就……',
    note: '考虑 là từ bài 5; 勇敢地 + V.' },
  '失败|1': { prompt: 'Người thành công tuy đều từng trải qua rất nhiều thất bại, nhưng khác người thường ở chỗ họ đã kiên trì đến cùng.',
    answer: '取得成功的人虽然都经历过许多失败，但是他们和普通人的区别就是坚持了下来。', pair: '虽然……但是……',
    note: '坚持下来 — bổ ngữ xu hướng 下来: trụ được đến cùng.' },
  '取|0': { prompt: 'Chính vì đã trải qua nhiều thất bại mà vẫn kiên trì, nên họ mới đạt được thành công.',
    answer: '正因为经历过许多失败还能坚持，所以他们才取得了成功。', pair: '因为……所以……',
    note: '取得成功 là kết hợp cố định, không nói 拿到成功.' },
  '取|1': { prompt: 'Vì anh ấy còn phải đi lấy vali, nên phiền bạn đợi thêm một chút.',
    answer: '因为他还得去取行李箱，所以麻烦你再等一下。', pair: '因为……所以……',
    note: '取 + đồ vật — đi lấy: 取钱, 取行李.' },
  '经历|0': { prompt: 'Mặc dù cô ấy đã trải qua rất nhiều thất bại, nhưng chưa bao giờ từ bỏ lựa chọn của mình.',
    answer: '尽管她经历过很多失败，但她从来没有放弃过自己的选择。', pair: '尽管……但……',
    note: '从来没 + V + 过 — chưa bao giờ.' },
  '经历|1': { prompt: 'Lý Tiến vừa nghe Trương Viễn kể chuyện thành công, vừa ghi lại vài chỗ quan trọng.',
    answer: '李进一边听张远聊成功经历，一边记下了几个重要的地方。', pair: '一边……一边……',
    note: '一边 A 一边 B — hai việc diễn ra cùng lúc.' },
  '许多|0': { prompt: 'Người đạt thành công không những từng trải qua nhiều thất bại, mà còn gặp vô số khó khăn.',
    answer: '取得成功的人不但经历过许多失败，而且还遇到过许多困难。', pair: '不但……而且……',
    note: '困难 là từ bài 2 — 遇到困难.' },
  '许多|1': { prompt: 'Cho dù cuối cùng thất bại, chúng ta vẫn học được rất nhiều điều bổ ích trong quá trình nỗ lực.',
    answer: '即使最后失败了，我们也能在努力的过程中学到许多有用的东西。', pair: '即使……也……',
    note: '即使……也…… — nhượng bộ giả định, khác 尽管 (việc có thật).' },
  '区别|0': { prompt: 'Người thành công và người bình thường khác nhau không phải ở may mắn, mà ở chỗ họ đã kiên trì đến cùng.',
    answer: '取得成功的人和普通人的区别不是运气，而是他们都坚持了下来。', pair: '不是……而是……',
    note: '不是 A，而是 B — phủ định A rồi khẳng định B.' },
  '区别|1': { prompt: 'Bạn có biết "希望" và "理想" khác nhau chỗ nào không? Nếu không biết thì tra từ điển đi.',
    answer: '你知道"希望"和"理想"有什么区别吗？要是不知道，就查一下词典吧。', pair: '要是……就……',
    note: 'A 和 B 有什么区别 — mẫu câu hỏi so sánh hai từ.' },
  '暂时|0': { prompt: 'Chỉ cần tin rằng mọi khó khăn đều chỉ là tạm thời, thì bạn nhất định sẽ thành công.',
    answer: '只要相信所有的困难都是暂时的，你就一定会成功。', pair: '只要……就……',
    note: '所有 là từ bài 6; 信心 (bài 3) và 暂时 hay đi cùng nhau khi động viên.' }
};
