// Viet lai cau luyen dich bai 12 thanh CAU GHEP co cap lien tu HSK 4.
module.exports = {
  '可惜|0': { prompt: 'Trận đấu hay thế mà bạn lại không xem, chẳng lẽ hôm đó bạn bận lắm sao? Tiếc quá!',
    answer: '这么精彩的比赛你竟然没看，难道那天你很忙吗？太可惜了！', pair: '难道……吗？',
    note: '精彩 là từ bài 11, 竟然 là từ bài 6.' },
  '可惜|1': { prompt: 'Vì cô ấy nói sẽ từ bỏ cơ hội du học, nên mọi người đều thấy rất đáng tiếc.',
    answer: '因为她表示要放弃留学的机会，所以大家都觉得很可惜。', pair: '因为……所以……',
    note: '表示 là từ bài 11, 放弃 là từ bài 9.' },
  '全部|1': { prompt: 'Nội dung trong sách không phải toàn bộ đều đúng, cho nên phải có quan điểm của riêng mình.',
    answer: '书上的内容不是全部都是对的，所以要有自己的看法。', pair: '因为……所以……',
    note: '内容, 看法 đều là từ bài 11 — quay lại ngay bài sau.' },
  '也许|1': { prompt: 'Anh ấy chưa tới, có lẽ do kẹt xe; chúng ta chỉ cần đợi thêm chút là anh ấy đến thôi.',
    answer: '他还没到，也许是由于堵车，只要再等一会儿，他就会来的。', pair: '只要……就……',
    note: '堵车 là từ bài 8, 由于 là từ bài 10.' },
  '商量|0': { prompt: 'Việc này tôi phải bàn với bố mẹ trước rồi mới quyết định.',
    answer: '这件事我得先跟父母商量一下，然后再做决定。', pair: '先……然后……',
    note: '跟 + ai + 商量 — giới từ 跟 dẫn đối tượng bàn bạc.' },
  '商量|1': { prompt: 'Vì nội dung quá đơn giản, không đủ chi tiết, nên mai chúng ta phải họp bàn lại.',
    answer: '因为内容太简单，不够详细，所以明天我们得再开会商量商量。', pair: '因为……所以……',
    note: '商量商量 — dạng lặp ABAB của từ hai âm tiết.' },
  '并且|0': { prompt: 'Anh ấy không những làm việc rất nghiêm túc, mà còn giàu kinh nghiệm, nên giao cho anh ấy phụ trách là hợp nhất.',
    answer: '他不但做事很认真，并且有丰富的经验，所以让他负责最合适。', pair: '不但……并且……',
    note: '经验 là từ bài 4, 负责 là từ bài 3.' },
  '并且|1': { prompt: 'Căn nhà này không những đồ đạc đều mới, mà giá cũng rẻ, thật đáng cân nhắc.',
    answer: '这房子不但家具都很新，并且价格也便宜，真的很值得考虑。', pair: '不但……并且……',
    note: '家具, 价格 là từ bài 5; 值得 là từ bài 6.' },
  '盐|0': { prompt: 'Muối chẳng phải dùng để nấu ăn sao? Chẳng lẽ nó còn giữ được màu quần áo?',
    answer: '盐不是用来做饭的吗？难道它还能让衣服不掉颜色？', pair: '难道……吗？',
    note: '掉 là từ bài 7 — 掉颜色 nghĩa là phai màu.' },
  '盐|1': { prompt: 'Chỉ cần cho chút muối vào nước lúc giặt là quần áo sẽ không phai màu.',
    answer: '只要洗的时候在水里加点儿盐，衣服就不会掉颜色了。', pair: '只要……就……',
    note: '在 + nơi chốn + 里 + 加 + N.' },
  '勺子|0': { prompt: 'Trẻ con ăn cơm bằng thìa không những dễ hơn dùng đũa, mà còn đỡ rơi vãi.',
    answer: '孩子用勺子吃饭不但比用筷子容易得多，而且还不容易掉。', pair: '不但……而且……',
    note: 'Adj + 得多 — hơn hẳn, chênh lệch lớn.' },
  '勺子|1': { prompt: 'Cho một thìa muối vào nước rồi giặt không những là cách đơn giản nhất, mà còn chẳng tốn tiền.',
    answer: '在水里加勺盐再洗不但是最简单的方法，而且一分钱也不用花。', pair: '不但……而且……',
    note: '一分钱也不 — phủ định nhấn mạnh.' },
  '保护|1': { prompt: 'Đây là lần đầu tôi nghe nói muối có tác dụng giữ màu quần áo, nên thấy rất bất ngờ.',
    answer: '因为我第一次听说盐有保护衣服颜色的作用，所以觉得很意外。', pair: '因为……所以……',
    note: '有 + V + N + 的作用 — có tác dụng làm gì.' },
  '作用|1': { prompt: 'Càng kiên trì đọc sách thì tác dụng đối với việc tăng kiến thức càng lớn.',
    answer: '阅读坚持得越久，对增加知识的作用就越大。', pair: '越……越……',
    note: '阅读, 增加 là từ bài 11 — quay lại nguyên cặp.' },
  '无法|0': { prompt: 'Chuyện đã xảy ra rồi, dù bạn có hối hận đến đâu cũng không thay đổi được.',
    answer: '事情已经发生了，即使你再后悔，也无法改变。', pair: '即使……也……',
    note: '发生 là từ bài 8, 后悔 là từ bài 7.' },
  '无法|1': { prompt: 'Vì lý do thời tiết, nên máy bay không thể cất cánh đúng giờ.',
    answer: '由于天气原因，所以飞机无法按时起飞。', pair: '由于……所以……',
    note: '按时 là từ bài 4 — 按时起飞.' },
  '节|0': { prompt: 'Vì nội dung tiết học này hơi phức tạp, nên thầy đã giải thích mấy lần.',
    answer: '因为这节课的内容有点儿复杂，所以老师解释了好几遍。', pair: '因为……所以……',
    note: '复杂 là từ bài 11; 一节课 — lượng từ 节 cho tiết học.' },
  '节|1': { prompt: 'Nghe xong tiết học này tôi mới hiểu vì sao giờ của thầy lại được yêu thích đến thế.',
    answer: '只有听完这节课，我才明白为什么您的课那么受欢迎。', pair: '只有……才……',
    note: '受欢迎 — 受到 (bài 5) rút gọn thành 受.' },
  '详细|0': { prompt: 'Nếu thầy có thời gian thì nói chi tiết giúp em về nhận xét đối với giờ dạy của em nhé.',
    answer: '要是您有时间，就详细谈谈对我的课的看法吧。', pair: '要是……就……',
    note: '看法 là từ bài 11 — 对……的看法.' },
  '详细|1': { prompt: 'Trước khi đi du lịch tốt nhất nên lập kế hoạch chi tiết, ví dụ đi mấy nơi, đi xe thế nào.',
    answer: '旅游前最好做个详细的计划，比如去几个地方、怎么坐车。', pair: '比如……',
    note: '比如 là từ bài 10, 计划 là từ bài 4.' },
  '解释|0': { prompt: 'Sau khi tôi giải thích với vị khách lý do không giao hàng kịp, cô ấy nói là có thể thông cảm.',
    answer: '我一向那位顾客解释了不能及时送货的原因，她就表示可以理解。', pair: '一……就……',
    note: '顾客 (bài 3), 及时 (bài 2), 理解 (bài 2) cùng xuất hiện lại.' },
  '对于|0': { prompt: 'Đối với việc này, quan điểm của tôi không những khác mọi người, mà còn hoàn toàn ngược lại.',
    answer: '对于这件事，我跟大家的看法不但不同，而且几乎完全相反。', pair: '不但……而且……',
    note: '对于 chỉ dẫn sự việc, không dẫn người: ✗ 对于他笑.' },
  '对于|1': { prompt: 'Đối với vấn đề này, chỉ khi cân nhắc thật kỹ bạn mới đưa ra được quyết định đúng.',
    answer: '对于这个问题，只有仔细考虑，你才能做出正确的决定。', pair: '只有……才……',
    note: '正确 là từ bài 9, 考虑 là từ bài 5.' },
  '叶子|0': { prompt: 'Trên đời không có hai chiếc lá hoàn toàn giống nhau, cũng như không có hai con người giống hệt nhau.',
    answer: '世界上不但没有完全相同的叶子，而且也没有完全一样的人。', pair: '不但……而且……',
    note: '相同 là từ bài 11 — 完全相同.' },
  '叶子|1': { prompt: 'Mùa thu vừa đến là lá trên cây đều chuyển đỏ.',
    answer: '秋天一到，树上的叶子就都变红了。', pair: '一……就……',
    note: '一 + V + 就 — vừa… là…' },
  '语言|0': { prompt: 'Tiểu thuyết của ông ấy không những ngôn ngữ hài hước, mà còn được dịch ra nhiều thứ tiếng.',
    answer: '他的小说不仅语言幽默，而且已经被翻译成了好几种语言。', pair: '不仅……而且……',
    note: '翻译 là từ bài 10, 幽默 là từ bài 1; câu bị động với 被.' },
  '语言|1': { prompt: 'Học một ngôn ngữ, quan trọng nhất không phải là học thuộc nhiều từ, mà là kiên trì dùng nó.',
    answer: '学习一门语言，最重要的不是记住很多词语，而是坚持使用它。', pair: '不是……而是……',
    note: '词语 là từ bài 11; 一门语言 — lượng từ 门.' },
  '直接|1': { prompt: 'Tôi gửi số vào điện thoại bạn, chỉ cần bạn liên hệ thẳng với anh ấy là được.',
    answer: '我把号码发到你手机上，只要你直接跟他联系就行。', pair: '只要……就……',
    note: '联系 là từ bài 2; câu chữ 把: 把 + tân ngữ + 发到 + nơi chốn.' },
  '引起|0': { prompt: 'Nguyên nhân và kết quả thường liên hệ với nhau: có nguyên nhân nào thì sẽ dẫn đến kết quả ấy.',
    answer: '原因和结果往往是互相联系的，有什么样的原因，就会引起什么样的结果。', pair: '……就……',
    note: '往往 là từ bài 8, 结果 là từ bài 9.' },
  '误会|0': { prompt: 'Bạn hiểu lầm tôi rồi, tôi không phải ý đó mà là muốn nhắc bạn thôi.',
    answer: '你误会我了，我不是那个意思，而是想提醒你一下。', pair: '不是……而是……',
    note: '提醒 là từ bài 4 — nhắc việc người ta đã biết nhưng dễ quên.' },
  '友好|0': { prompt: 'Nhắc người khác bằng thái độ thân thiện thì hiệu quả thường tốt hơn nhiều so với nói thẳng.',
    answer: '用友好的态度提醒别人，效果往往比直接说出来好得多。', pair: '比……好得多',
    note: '态度 là từ bài 8, 效果 là từ bài 5.' },
  '友好|1': { prompt: 'Người như vậy không những khiến người khác thấy thân thiện, mà còn dễ kết bạn hơn.',
    answer: '这样的人不但会让人觉得更友好，而且也更容易交到朋友。', pair: '不但……而且……',
    note: '交朋友 là từ bài 2 — 交到朋友.' },
  '力气|0': { prompt: 'Chúng mình nghỉ ở đây một lát đi, vì tôi thật sự không còn sức leo nữa.',
    answer: '咱们在这儿休息一会儿吧，因为我实在没力气爬了。', pair: '因为……',
    note: '咱们 là từ bài 3, 实在 là từ bài 5.' },
  '相反|0': { prompt: 'Vì kết quả khảo sát gần như trái ngược hẳn với điều họ nghĩ, nên họ buộc phải đổi kế hoạch ban đầu.',
    answer: '因为调查结果和他们想的几乎完全相反，所以他们不得不改变原来的计划。', pair: '因为……所以……',
    note: '调查, 不得不, 原来的计划 đều là từ bài 4.' },
  '任务|1': { prompt: 'Nhiệm vụ tháng này không những đã hoàn thành toàn bộ, mà còn xong sớm hơn dự định.',
    answer: '这个月的任务不但已经全部完成了，而且还提前完成了。', pair: '不但……而且……',
    note: '提前 là từ bài 4 — 提前完成.' }
};
