// Viet lai cau luyen dich bai 10 thanh CAU GHEP co cap lien tu HSK 4.
module.exports = {
  '礼拜天|0': { prompt: 'Nếu chủ nhật này bạn rảnh thì đi cùng tôi mua quà sinh nhật cho chồng nhé.',
    answer: '要是这个礼拜天你有空儿，就陪我去买丈夫的生日礼物吧。', pair: '要是……就……',
    note: '陪 là từ bài 2 — 陪 + ai + V.' },
  '礼拜天|1': { prompt: 'Tôi định chủ nhật đi thăm bố mẹ, nếu bạn rảnh thì đi cùng luôn.',
    answer: '我打算礼拜天去看望父母，要是你有空儿，就一起去吧。', pair: '要是……就……',
    note: '礼拜天 ≈ 星期天, thiên khẩu ngữ.' },
  '空儿|0': { prompt: 'Dạo này bạn bận không? Hôm nào rảnh thì chúng mình đi uống trà nhé.',
    answer: '你最近忙吗？哪天有空儿，咱们就一起去喝茶吧。', pair: '……就……',
    note: '咱们 là từ bài 3 — rủ rê, gồm cả người nghe.' },
  '空儿|1': { prompt: 'Tuy hôm nay tôi không rảnh, nhưng hôm khác nhất định sẽ đi cùng bạn.',
    answer: '虽然我今天没空儿，但是改天一定陪你去。', pair: '虽然……但是……',
    note: '改天 — hôm khác, dùng khi hẹn lại.' },
  '不过|1': { prompt: 'Năm ngoái tôi chỉ nặng chưa tới 50 cân, sao năm nay ăn càng nhiều lại càng béo thế này?',
    answer: '去年我不过50公斤，今年怎么越吃越胖了？', pair: '越……越……',
    note: '不过 + số lượng — chỉ, chưa tới (phó từ).' },
  '永远|1': { prompt: 'Chúng không những chẳng vì chuyện hôm qua mà phiền lòng, mà còn chẳng lo chuyện ngày mai.',
    answer: '它们不但永远不为昨天的事烦恼，而且也不为明天的事担心。', pair: '不但……而且……',
    note: '烦恼 là từ bài 7; 为 + N + 烦恼 — phiền lòng vì cái gì.' },
  '方向|0': { prompt: 'Chính vì trong lòng có mẹ và con cần chăm lo, nên cô ấy mới có được hướng đi để cố gắng.',
    answer: '正因为心里有母亲和孩子需要照顾，所以她才有了努力的方向。', pair: '因为……所以……',
    note: '母亲 trang trọng hơn 妈妈, dùng khi kể chuyện.' },
  '优秀|0': { prompt: 'Con gái bạn không những xinh đẹp lại xuất sắc, mà tốt nghiệp thạc sĩ xong là có ngay việc tốt.',
    answer: '你女儿不但漂亮又优秀，而且硕士毕业后就有了好工作。', pair: '不但……而且……',
    note: '毕业 là từ bài 2 — từ ly hợp, không mang tân ngữ.' },
  '优秀|1': { prompt: 'Chính vì anh ấy là một phiên dịch xuất sắc, nên rất được mọi người tôn trọng.',
    answer: '正因为他是一位优秀的翻译，所以很受大家尊重。', pair: '因为……所以……',
    note: '受 + N — chịu, được; 位 là lượng từ lịch sự.' },
  '硕士|0': { prompt: 'Cô ấy đang học thạc sĩ, chỉ cần tốt nghiệp là sẽ đi làm phiên dịch.',
    answer: '她正在读硕士，只要毕业，就打算去当翻译。', pair: '只要……就……',
    note: '读硕士 — học cao học; 当 + nghề nghiệp.' },
  '硕士|1': { prompt: 'Anh bạn chẳng phải nói ba giờ đến sao? Đã quá nửa tiếng rồi mà sao vẫn chưa ra?',
    answer: '你哥不是说三点到吗？虽然已经过去半个小时了，但是怎么还没出来？', pair: '虽然……但是……',
    note: '不是……吗？ — câu hỏi tu từ, ý nhắc lại điều đã biết.' },
  '翻译|0': { prompt: 'Con gái tôi không những tốt nghiệp thạc sĩ xong là làm phiên dịch ngay, mà công việc còn làm rất xuất sắc.',
    answer: '我女儿不但硕士毕业后就当了翻译，而且工作做得很优秀。', pair: '不但……而且……',
    note: 'V + 得 + Adj — bổ ngữ trạng thái.' },
  '翻译|1': { prompt: 'Cô ấy không những muốn dịch quyển tiểu thuyết này sang tiếng Trung, mà còn muốn tự viết một cuốn.',
    answer: '她不仅想把这本小说翻译成中文，而且还想自己写一本。', pair: '不仅……而且……',
    note: '把 + N + 翻译成 + ngôn ngữ — câu chữ 把.' },
  '确实|0': { prompt: 'Tình yêu quả thực là lý do quan trọng để kết hôn, nhưng chỉ có tình yêu thôi thì chưa đủ.',
    answer: '爱情确实是结婚的重要原因，可是仅有爱情是不够的。', pair: '虽然……可是……',
    note: '爱情, 结婚 là từ bài 1 — ôn lại ở bài nói về hạnh phúc.' },
  '确实|1': { prompt: 'Con gái tôi quả thực khá lắm, chỉ cần tốt nghiệp thạc sĩ là có ngay việc tốt.',
    answer: '我女儿确实不错，只要硕士一毕业，就有了好工作。', pair: '一……就……',
    note: '确实 xác nhận điều người khác vừa khen.' },
  '兴奋|0': { prompt: 'Mọi người vừa nghe tin vui này là ai nấy đều phấn khởi.',
    answer: '大家一听到这个好消息，就都很兴奋。', pair: '一……就……',
    note: '消息 là từ bài 4 — 听到消息.' },
  '拉|1': { prompt: 'Cô ấy vừa nhận lương là hào hứng kéo tôi đi mua sắm ngay.',
    answer: '她一拿到工资，就兴奋地拉着我去购物。', pair: '一……就……',
    note: '工资 là từ bài 4, 购物 là từ bài 5.' },
  '建议|0': { prompt: 'Vì tôi vẫn chưa nghĩ ra nên chọn nghề gì, nên đang muốn nghe góp ý của bạn.',
    answer: '因为我还没想好该选择什么职业，所以正想听听你的建议。', pair: '因为……所以……',
    note: '听听 — động từ lặp, nghe nhẹ nhàng hơn.' },
  '建议|1': { prompt: 'Bạn tôi khuyên tôi nên lái xe ra ngoài nhiều hơn, vì lái càng nhiều thì càng quen đường.',
    answer: '朋友建议我平时多开车出去走走，因为开得越多，对道路就越熟悉。', pair: '越……越……',
    note: '熟悉 là từ bài 1 — 对 + N + 熟悉.' },
  '职业|0': { prompt: 'Bạn thấy khi chọn nghề, là tiền lương quan trọng hơn hay hứng thú quan trọng hơn?',
    answer: '你觉得在选择职业时，不是工资更重要，而是兴趣更重要吗？', pair: '不是……而是……',
    note: '在……时 — khi làm gì, thiên văn viết hơn 的时候.' },
  '职业|1': { prompt: 'Bất kể là nghề nào, cũng đều có ưu điểm và khuyết điểm riêng.',
    answer: '不管是什么职业，都有自己的优点和缺点。', pair: '不管……都……',
    note: '优点 là từ bài 5, 缺点 là từ bài 1.' },
  '关键|1': { prompt: 'Mấu chốt để giảm cân thành công không phải là giảm một tháng, mà là kiên trì lâu dài.',
    answer: '减肥成功的关键不是只减一个月，而是长期坚持。', pair: '不是……而是……',
    note: '减肥 là từ bài 7, 坚持 là từ bài 9.' },
  '将来|1': { prompt: 'Bạn có dự định gì cho tương lai? Nếu chưa nghĩ ra thì cùng bàn với tôi nhé.',
    answer: '你对将来有什么打算？要是还没想好，就跟我一起商量商量吧。', pair: '要是……就……',
    note: '商量商量 — động từ hai âm tiết lặp theo kiểu ABAB.' },
  '躺|0': { prompt: 'Tôi thấy chỉ cần đi làm về tắm nước nóng rồi nằm đọc sách nghe nhạc, buồn ngủ thì ngủ, là đã rất hạnh phúc.',
    answer: '我觉得只要工作结束回家后洗个热水澡，躺在床上看看书、听听音乐，困了就睡觉，那就很幸福。', pair: '只要……就……',
    note: '幸福 là từ bài 1; 躺在 + nơi chốn + 上.' },
  '躺|1': { prompt: 'Trong phòng tối thế mà sao không bật đèn? Chẳng lẽ bạn không khỏe nên đang nằm nghỉ?',
    answer: '房间里这么暗，怎么不开灯呀？难道你身体不舒服，正躺着休息吗？', pair: '难道……吗？',
    note: '难道……吗？ — câu hỏi tu từ (bài 9).' },
  '困|1': { prompt: 'Vì hôm nay tôi rất buồn ngủ, nên muốn nằm trên giường ngủ một lát.',
    answer: '因为我今天很困，所以想躺在床上睡一会儿。', pair: '因为……所以……',
    note: '困 là buồn ngủ, khác 累 (mệt).' },
  '经济|1': { prompt: 'Mấy năm nay kinh tế đất nước càng phát triển nhanh thì cuộc sống người dân càng tốt lên.',
    answer: '这几年国家的经济发展得越快，人们的生活就越好。', pair: '越……越……',
    note: 'V + 得 + 越 + Adj — hai vế biến đổi cùng chiều.' },
  '等|1': { prompt: 'Chúng ta không những cần chuẩn bị hồ sơ, hộ chiếu, tiền mặt, v.v., mà còn phải đến sớm một chút.',
    answer: '我们不但需要准备材料、护照、现金等，而且还得早点儿到。', pair: '不但……而且……',
    note: '等 đặt CUỐI danh sách: A、B、C 等.' },
  '由于|0': { prompt: 'Vì nhiều nguyên nhân, nên chúng tôi buộc phải thay đổi kế hoạch ban đầu.',
    answer: '由于种种原因，所以我们不得不改变原来的计划。', pair: '由于……所以……',
    note: '不得不 và 原来的计划 đều là từ bài 4.' },
  '比如|0': { prompt: 'Mỗi người đều có sở thích riêng, chẳng hạn nhà văn thì thích viết tiểu thuyết, còn hoạ sĩ thì thích vẽ tranh.',
    answer: '每个人都有自己特别的爱好，比如作家爱写小说，而画家爱画画儿。', pair: '……，而……',
    note: '作家, 小说 là từ bài 9 và bài 6.' },
  '比如|1': { prompt: 'Có lúc đồ chất lượng tốt cũng rất rẻ, chẳng hạn cứ sang xuân là quần áo mùa đông giảm giá.',
    answer: '有时候质量很好的东西也会很便宜，比如春天一来，冬天的衣服就会打折。', pair: '一……就……',
    note: '质量, 打折 là từ bài 5.' },
  '橡皮|1': { prompt: 'Tôi quên mang tẩy rồi, nếu bạn có thừa thì cho tôi mượn một cái nhé.',
    answer: '我忘带橡皮了，要是你有多余的，就借我一块吧。', pair: '要是……就……',
    note: '一块橡皮 / 一块糖 — cùng lượng từ 块.' },
  '低|0': { prompt: 'Vì trình độ chơi bóng của hai người họ ngang nhau, nên rất khó phân cao thấp.',
    answer: '因为他们两个人打球的水平差不多，所以很难分出高低。', pair: '因为……所以……',
    note: '差不多 là từ bài 2 — gần như nhau.' },
  '低|1': { prompt: 'Thái độ sống của một người quyết định mức độ hạnh phúc cao hay thấp: thái độ càng tích cực thì cảm giác hạnh phúc càng cao.',
    answer: '一个人的生活态度决定了他幸福感的高低，态度越积极，幸福感就越高。', pair: '越……越……',
    note: '态度, 积极 là từ bài 8 — quay lại nguyên cặp.' }
};
