// Viet lai cau luyen dich bai 8 thanh CAU GHEP co cap lien tu HSK 4.
module.exports = {
  '巧克力|0': { prompt: 'Không những rất nhiều người thích ăn sô cô la, mà phụ nữ lại càng thích.',
    answer: '不但很多人都爱吃巧克力，而且女性更喜欢。', pair: '不但……而且……',
    note: '尤其 (bài 5) và 更 đều nhấn cái nổi bật trong nhóm.' },
  '巧克力|1': { prompt: 'Cô ấy không những tặng tôi một hộp sô cô la mang từ nước ngoài về, mà còn viết cho tôi một tấm thiệp.',
    answer: '她不仅送给我一盒从国外带回来的巧克力，而且还给我写了一张卡片。', pair: '不仅……而且……',
    note: '送给 + ai + N — tặng ai cái gì; 盒 là lượng từ cho hộp.' },
  '亲戚|0': { prompt: 'Rất nhiều người cứ đi du lịch nước ngoài về là mua quà tặng họ hàng bạn bè.',
    answer: '很多人一出国旅游回来，就会买礼物送给亲戚朋友。', pair: '一……就……',
    note: '一 + V + 就 + V — vừa làm xong việc này là làm việc kia.' },
  '亲戚|1': { prompt: 'Vì anh ấy chỉ là một người họ hàng xa, nên chúng tôi rất ít khi liên lạc.',
    answer: '因为他只是我的一个远房亲戚，所以我们很少联系。', pair: '因为……所以……',
    note: '联系 là từ bài 2 — 跟……联系.' },
  '伤心|0': { prompt: 'Nghe nói chỉ cần ăn một miếng sô cô la lúc buồn là tâm trạng sẽ vui lên một chút.',
    answer: '听说只要伤心的时候吃一块巧克力，心情就会变得愉快一些。', pair: '只要……就……',
    note: '变得 + Adj — trở nên thế nào.' },
  '使|0': { prompt: 'Trong phòng nên đặt thêm cây xanh, vì cây xanh làm không khí trong lành hơn.',
    answer: '房间里应该多放一些绿色植物，因为绿色植物能使空气变得更新鲜。', pair: '因为……',
    note: '使 phải có CHỦ NGỮ đứng trước — đây là chỗ hay viết thiếu.' },
  '使|1': { prompt: 'Chuyện này không những khiến tôi hiểu ra nhiều đạo lý, mà còn làm tôi thay đổi cách nhìn.',
    answer: '这件事不但使我明白了很多道理，而且还使我改变了看法。', pair: '不但……而且……',
    note: '✗ 听完这件事，使我明白 → ✓ 这件事使我明白: 使 cần chủ ngữ.' },
  '心情|0': { prompt: 'Tâm trạng đỡ hơn chưa? Tuy lần trước thua, nhưng bạn đá đã rất tốt rồi.',
    answer: '心情好些了吗？虽然上次输了，但是你踢得已经很好了。', pair: '虽然……但是……',
    note: 'V + 得 + Adj — bổ ngữ trạng thái đánh giá cách làm.' },
  '愉快|0': { prompt: 'Không những màu vàng và trắng khiến tâm trạng vui vẻ, mà màu xanh cũng làm người ta thư giãn.',
    answer: '不但黄色和白色让人心情变得愉快，而且绿色也能使人放松。', pair: '不但……而且……',
    note: '让 / 使 đều là câu kiêm ngữ; 让 thiên khẩu ngữ hơn.' },
  '愉快|1': { prompt: 'Chỉ cần ăn một miếng sô cô la là tâm trạng người ta sẽ vui vẻ hơn.',
    answer: '只要吃一块巧克力，人的心情就能变得更愉快。', pair: '只要……就……',
    note: '愉快 chỉ trạng thái kéo dài, 高兴 chỉ lúc đó.' },
  '景色|0': { prompt: 'Nơi đây không những phong cảnh thật đẹp, mà không khí cũng rất trong lành.',
    answer: '这里不但景色真美，而且空气也很新鲜。', pair: '不但……而且……',
    note: '空气新鲜 là từ bài 7 — quay lại ở ngữ cảnh du lịch.' },
  '景色|1': { prompt: 'Từ khi anh ấy dẫn tôi đến ngắm cảnh nơi này, tâm trạng tôi đã tốt hơn nhiều.',
    answer: '自从他带我来看这里的景色，我的心情就好多了。', pair: '自从……就……',
    note: '自从 + mốc thời gian，就…… — từ khi nào trở đi.' },
  '放松|0': { prompt: 'Từ sau khi thi xong tôi mới thấy thoải mái, đã lâu rồi không được thư giãn như vậy.',
    answer: '只有考完试以后，我才觉得轻松，好久都没这么放松了。', pair: '只有……才……',
    note: '放松 ↔ 紧张 (bài 3).' },
  '放松|1': { prompt: 'Cuối tuần cùng gia đình đi dạo công viên vừa thư giãn được tâm trạng, vừa rèn luyện được sức khỏe.',
    answer: '周末和家人一起去公园散步，既可以放松心情，又可以锻炼身体。', pair: '既……又……',
    note: '散步 là từ bài 7; 既……又…… nêu hai cái lợi cùng lúc.' },
  '压力|1': { prompt: 'Vì công việc này áp lực rất lớn, nên tôi cần tìm cách thư giãn bản thân.',
    answer: '因为这份工作压力很大，所以我需要找办法放松自己。', pair: '因为……所以……',
    note: '压力 đi với 大 / 小, không đi với 多 / 少.' },
  '发生|1': { prompt: 'Bất kể chuẩn bị kỹ đến đâu, cũng không ai biết trước được sau này sẽ xảy ra chuyện gì.',
    answer: '不管准备得多好，都没人能提前知道以后会发生什么事。', pair: '不管……都……',
    note: '提前 là từ bài 4 — biết trước, làm trước.' },
  '成为|0': { prompt: 'Chính vì anh ấy đã trở thành một luật sư nổi tiếng, nên cuối cùng chứng minh được với mọi người rằng lựa chọn của mình là đúng.',
    answer: '正因为他现在已经成为一个有名的律师，所以终于向大家证明了自己的选择是对的。', pair: '因为……所以……',
    note: '律师 là từ bài 3; 向 + ai + 证明.' },
  '师傅|0': { prompt: 'Bác tài ơi, nếu đường này đúng thì phiền bác chở tôi đến đại sứ quán.',
    answer: '师傅，要是这条路对，就麻烦您送我去大使馆。', pair: '要是……就……',
    note: '师傅 là cách gọi lịch sự tài xế, thợ; khác 老师.' },
  '师傅|1': { prompt: 'Cảm ơn bác tài, bác không những lái xe rất cẩn thận, mà còn chọn được đường không kẹt xe.',
    answer: '谢谢师傅，您不但开车开得很小心，而且还选了一条不堵车的路。', pair: '不但……而且……',
    note: '开车开得很小心 — từ ly hợp lặp động từ để mang bổ ngữ.' },
  '大使馆|0': { prompt: 'Vì tôi cần đến đại sứ quán làm visa, nên muốn hỏi xem đường này có đúng không.',
    answer: '因为我需要去大使馆办签证，所以想问问这条路对不对。', pair: '因为……所以……',
    note: '对不对 — dạng hỏi chính phản làm tân ngữ.' },
  '大使馆|1': { prompt: 'Vì bác tài nói phía trước kẹt xe, nên chúng tôi đi đường khác đến đại sứ quán.',
    answer: '因为师傅说前面堵车，所以我们走另外一条路去大使馆。', pair: '因为……所以……',
    note: '另外一条路 — 另外 là từ bài 3.' },
  '堵车|0': { prompt: 'Bây giờ đang giờ tan tầm, tuy phía trước kẹt xe, nhưng khoảng cách hai đường xấp xỉ nhau.',
    answer: '现在是下班时间，虽然前面堵车，但是两条路的距离差不多。', pair: '虽然……但是……',
    note: '差不多 là từ bài 2 — gần như nhau.' },
  '堵车|1': { prompt: 'Ngày nào cũng lái xe trên đường, muốn không gặp kẹt xe thì quả thật rất khó.',
    answer: '每天在马路上开车，要是想不遇到堵车，那就真难了。', pair: '要是……就……',
    note: '堵车 là từ ly hợp: 堵了半小时车.' },
  '距离|0': { prompt: 'Chỉ cần đi đường khác là được, khoảng cách xấp xỉ nhau nên sẽ không muộn đâu.',
    answer: '只要我们走另外一条路就行，距离差不多，不会迟到的。', pair: '只要……就……',
    note: '……就行 — như vậy là được rồi.' },
  '耐心|1': { prompt: 'Giám đốc bảo tôi đừng vội, chỉ cần kiên nhẫn chờ tin là được.',
    answer: '经理让我别着急，只要耐心等消息就行了。', pair: '只要……就……',
    note: '消息 là từ bài 4; 耐心地 + V — làm gì một cách kiên nhẫn.' },
  '生命|0': { prompt: 'Cỏ xanh rồi, đó là màu của sự sống; hoa nở rồi, đó là món quà của thiên nhiên — chỉ cần chịu nhìn là thấy cái đẹp ở khắp nơi.',
    answer: '草绿了，那是生命的颜色；花开了，那是大自然的礼物——只要愿意看，到处都是美。', pair: '只要……都……',
    note: '到处都是 — đâu đâu cũng có.' },
  '生命|1': { prompt: 'Chúng ta không những nên trân trọng sự sống, mà còn phải sống một cuộc đời có ý nghĩa.',
    answer: '我们不但应该珍惜生命，而且要过有意义的生活。', pair: '不但……而且……',
    note: '生命 là sinh mệnh, 生活 là đời sống — hai từ dễ nhầm.' },
  '缺少|1': { prompt: 'Vì kế hoạch này thiếu tài liệu cụ thể, nên cần bổ sung thêm.',
    answer: '因为这个计划缺少具体的材料，所以需要再补充一下。', pair: '因为……所以……',
    note: '计划 là từ bài 4, 材料 là từ bài 3.' },
  '到处|1': { prompt: 'Đồ trong phòng cậu sao lại vứt bừa khắp nơi thế, nếu không dọn thì lát nữa không tìm thấy đâu.',
    answer: '你房间里的东西怎么到处乱放，要是不收拾，一会儿就找不到了。', pair: '要是……就……',
    note: 'V + 不到 — bổ ngữ khả năng phủ định: không tìm ra.' },
  '态度|1': { prompt: 'Thái độ sống tích cực không những là điểm chung của các cô gái thích mặc màu trắng, mà còn khiến họ trông tươi sáng hơn.',
    answer: '生活态度积极不但是喜欢穿白色衣服的女孩子的共同特点，而且还让她们看上去更阳光。', pair: '不但……而且……',
    note: '共同 là từ bài 1; 阳光 ở đây là tính cách, không phải ánh nắng.' },
  '科学|0': { prompt: 'Nghiên cứu khoa học chứng minh rằng chỉ cần tâm trạng vui vẻ là sức khỏe sẽ tốt hơn.',
    answer: '科学研究证明，只要心情愉快，身体就会更健康。', pair: '只要……就……',
    note: '研究 là từ bài 7 — 研究证明 / 研究发现.' },
  '证明|0': { prompt: 'Nghiên cứu khoa học chứng minh, đọc sách càng nhiều thì tư duy phát triển càng tốt.',
    answer: '科学研究证明，书读得越多，思维发展就越好。', pair: '越……越……',
    note: 'V + 得 + 越 + Adj — hai vế biến đổi cùng chiều.' },
  '证明|1': { prompt: 'Anh ấy không những chứng minh được với mọi người rằng lựa chọn của mình là đúng, mà còn khiến bố mẹ tự hào.',
    answer: '他不仅向大家证明了自己的选择是对的，而且还让父母感到骄傲。', pair: '不仅……而且……',
    note: '向 + ai + 证明 + mệnh đề.' },
  '往往|0': { prompt: 'Tài xế taxi càng có kinh nghiệm thì càng quen thuộc với tình hình đường sá.',
    answer: '出租车司机的经验越丰富，往往对道路情况就越熟悉。', pair: '越……越……',
    note: '往往 nêu quy luật, khác 常常 chỉ tần suất.' },
  '阳光|0': { prompt: 'Các cô gái thích mặc đồ trắng không những tính cách khá tươi sáng, mà thái độ sống tích cực cũng là điểm chung của họ.',
    answer: '喜欢穿白色衣服的女孩子不但性格比较阳光，而且生活态度积极向上也是她们的共同特点。', pair: '不但……而且……',
    note: '积极向上 — cụm cố định chỉ thái độ vươn lên.' },
  '积极|0': { prompt: 'Vì hội chợ tuyển dụng lần này có gần 1000 cơ hội việc làm, nên mong các bạn tích cực tham gia.',
    answer: '因为这次招聘会提供了差不多1000个工作机会，所以请同学们积极参加。', pair: '因为……所以……',
    note: '招聘会, 提供 là từ bài 3 — quay lại nguyên cụm.' },
  '积极|1': { prompt: 'Thái độ sống càng tích cực thì con người càng trở nên tươi sáng.',
    answer: '生活态度越积极，人就变得越阳光。', pair: '越……越……',
    note: '变得 + Adj — trở nên thế nào.' },
  '特点|1': { prompt: 'Không những thái độ sống tích cực, mà lạc quan cũng là điểm chung của họ.',
    answer: '不但生活态度积极，而且阳光也是他们的共同特点。', pair: '不但……而且……',
    note: '特点 đi với 共同 / 最大的 — 共同特点 là kết hợp hay gặp.' }
};
