// Viet lai cau luyen dich bai 15 thanh CAU GHEP co cap lien tu HSK 4.
module.exports = {
  '棒|0': { prompt: 'Tuyệt quá! Đã là mai không phải tăng ca thì chúng ta đi xem phim đi.',
    answer: '太棒了！既然明天不用加班，我们就去看电影吧。', pair: '既然……就……',
    note: '加班 là từ bài 1; 既然 nêu điều cả hai đã biết.' },
  '寒假|0': { prompt: 'Vì đã nghỉ đông rồi, nên người đi chơi bóng chắc chắn không nhiều.',
    answer: '因为已经放寒假了，所以去打球的人肯定不多。', pair: '因为……所以……',
    note: '肯定 là từ bài 5 — ở đây là phó từ.' },
  '闹钟|0': { prompt: 'Vì tối qua ngủ quá muộn, nên sáng nay báo thức reo mấy lượt tôi đều không nghe thấy.',
    answer: '因为昨晚睡得太晚，所以早上闹钟响了好几遍我都没听见。', pair: '因为……所以……',
    note: '遍 là từ bài 13 — đếm trọn một lượt.' },
  '响|0': { prompt: 'Điện thoại cứ reo mãi trên bàn là của ai vậy? Chắc là có việc gấp tìm anh ấy.',
    answer: '桌子上那个一直在响的手机是谁的呀？大概是有什么急事找他吧。', pair: '大概……',
    note: '在 + V + 的 — định ngữ chỉ việc đang diễn ra.' },
  '醒|0': { prompt: 'Vì mai tôi phải cho kịp chuyến bay, nên sáu giờ sáng bạn gọi tôi dậy nhé.',
    answer: '因为明天我得赶飞机，所以早上六点你就把我叫醒吧。', pair: '因为……所以……',
    note: '把 + ai + 叫醒 — 醒 làm bổ ngữ kết quả.' },
  '赶|0': { prompt: 'Khoảng một nửa thôi, nhưng Lý Tiến còn đặc biệt từ nước ngoài bay về cho kịp.',
    answer: '大约有一半吧，不过李进还专门从国外赶回来呢。', pair: '……，不过……',
    note: '大约 là từ bài 13, 专门 là từ bài 2.' },
  '厕所|0': { prompt: 'Trước khi xuất phát đi vệ sinh đã, vì trên đường phải chạy ba tiếng đấy.',
    answer: '出发前先去一下厕所，因为路上要开三个小时呢。', pair: '因为……',
    note: '上厕所 dùng động từ 上; 卫生间 (bài 14) lịch sự hơn.' },
  '弄|0': { prompt: 'Lát nữa khiêng sô pha thì cẩn thận một chút, nếu không lại làm hỏng mất.',
    answer: '一会儿搬沙发的时候要小心点儿，不然就弄坏了。', pair: '不然……',
    note: '沙发 là từ bài 5; 弄 + bổ ngữ kết quả: 弄坏 / 弄脏.' },
  '管理|0': { prompt: 'Bạn nên để con học cách quản lý thời gian, vì tự quản được thì mới tiến bộ.',
    answer: '你应该让孩子学会管理时间，因为只有自己管好，他才会进步。', pair: '只有……才……',
    note: '让 + ai + V — câu kiêm ngữ.' },
  '护士|0': { prompt: 'Ông cứ tưởng lớn lên tôi sẽ làm giáo viên, ai ngờ tôi lại trở thành y tá.',
    answer: '他以为我长大后会当老师，没想到我竟然成为了一名护士。', pair: '以为……没想到……',
    note: '成为 là từ bài 8, 竟然 là từ bài 6.' },
  '表扬|0': { prompt: 'Hoá ra động viên và khen ngợi khá có ích với trẻ, nên lần sau tôi cũng thử xem.',
    answer: '原来鼓励和表扬对小孩儿挺有用的，所以下次我也试试。', pair: '因为……所以……',
    note: '原来 là từ bài 4, 鼓励 là từ bài 14.' },
  '表扬|1': { prompt: 'Trẻ càng được khen thì càng tự tin và càng hứng thú với việc học.',
    answer: '孩子受到的表扬越多，就越对自己有信心，对学习的兴趣也越大。', pair: '越……越……',
    note: '信心 là từ bài 3 — 对自己有信心.' },
  '千万|0': { prompt: 'Bây giờ bạn tuyệt đối đừng nói cho cô ấy, nếu không cô ấy sẽ buồn lắm.',
    answer: '你现在千万别告诉她，不然她会很伤心的。', pair: '不然……',
    note: '伤心 là từ bài 8; 千万 hầu như chỉ dùng trong lời dặn phủ định.' },
  '千万|1': { prompt: 'Có những việc phải kiên trì mới thấy hy vọng, cho nên bạn tuyệt đối đừng bỏ cuộc.',
    answer: '有些事情只有坚持了，才会看到希望，所以你千万不要放弃。', pair: '只有……才……',
    note: '坚持 và 放弃 đều là từ bài 9 — cặp trái nghĩa.' },
  '怀疑|0': { prompt: 'Lúc thất bại đừng nghi ngờ bản thân, chỉ cần kiên trì là nhất định sẽ thành công.',
    answer: '失败的时候不要怀疑自己，只要坚持下去，就一定能成功。', pair: '只要……就……',
    note: '失败 là từ bài 9; 坚持下去 — bổ ngữ xu hướng 下去.' },
  '故意|0': { prompt: 'Yên tâm đi, bạn đâu có cố ý; chỉ cần đi giải thích với cô ấy là cô ấy sẽ hiểu thôi.',
    answer: '放心吧，你也不是故意的，只要去跟她解释一下，她就会理解的。', pair: '只要……就……',
    note: '解释 là từ bài 12, 理解 là từ bài 2 — hai từ dễ nhầm.' },
  '敲|0': { prompt: 'Trước khi vào phòng người khác thì phải gõ cửa, vì đó là phép lịch sự cơ bản nhất.',
    answer: '进别人的房间之前应该先敲门，因为这是最基本的礼貌。', pair: '因为……',
    note: '敲门 — 敲 + 了 + số + 下 khi đếm số cái gõ.' },
  '合适|0': { prompt: 'Nghe nói hội chợ tuyển dụng hôm qua nhiều cơ hội lắm, bạn tìm được công ty phù hợp chưa?',
    answer: '听说昨天那个招聘会提供了很多工作机会，那你找到合适的公司了吗？', pair: '既然……那……',
    note: '招聘会 và 提供 đều là từ bài 3.' },
  '骗|0': { prompt: 'Mua sắm trên mạng phải cẩn thận, nếu không thì rất dễ bị lừa.',
    answer: '网上购物要小心，不然很容易被骗。', pair: '不然……',
    note: '购物 là từ bài 5; 被 + 骗 — câu bị động.' },
  '儿童|0': { prompt: 'Trẻ khoảng bảy tuổi không những hiếu động, mà còn ngồi không yên.',
    answer: '七岁左右的儿童不但普遍好动，而且坐不住。', pair: '不但……而且……',
    note: '普遍 là từ bài 13; V + 不住 — không giữ được.' },
  '假|0': { prompt: 'Tin này là giả, cho nên bạn tuyệt đối đừng tin.',
    answer: '这个消息是假的，所以你千万别相信。', pair: '因为……所以……',
    note: '消息 là từ bài 4; 假 (jiǎ) khác 假 (jià) trong 寒假.' },
  '左右|0': { prompt: 'Cuốn sách mua trên mạng ước chừng ba ngày là tới, nếu chưa tới thì gọi cho họ.',
    answer: '网上买的那本书估计三天左右就能到，要是没到，就给他们打电话。', pair: '要是……就……',
    note: '估计 là từ bài 7; 左右 đứng SAU số lượng.' },
  '左右|1': { prompt: 'Giám đốc Mã cuối tháng 7 đi Bắc Kinh công tác, khoảng một tuần thì về.',
    answer: '马经理7月底去北京出差，大约一个星期左右就回来。', pair: '大约……',
    note: '出差 là từ bài 14 — 去 + nơi chốn + 出差.' },
  '笨|0': { prompt: 'Cậu ấy không hề ngốc, chỉ là phương pháp học chưa đúng thôi.',
    answer: '他并不笨，只是学习方法不对而已。', pair: '不是……而是……',
    note: '并不 là từ bài 4, 方法 là từ bài 4.' },
  '粗心|0': { prompt: 'Ưu điểm của anh ấy là lễ phép và thành thật, nhưng quá cẩu thả nên không hợp với công việc ở đây.',
    answer: '他的优点虽然是有礼貌、诚实，但是太粗心了，所以不适合这儿的工作。', pair: '虽然……但是……',
    note: '优点 là từ bài 5, 诚实 là từ bài 3; 粗心 ↔ 仔细 (bài 12).' }
};
