// Viet lai cau luyen dich bai 13 thanh CAU GHEP co cap lien tu HSK 4.
module.exports = {
  '京剧|0': { prompt: 'Ông bạn hát Kinh kịch chuyên nghiệp đến mức tôi cứ tưởng ông là diễn viên Kinh kịch, ai ngờ chỉ là người yêu thích.',
    answer: '你爷爷京剧唱得真专业，我本来以为他是京剧演员，没想到他只是个爱好者。', pair: '以为……没想到……',
    note: '专业 là từ bài 3 — ở đây là tính từ "chuyên nghiệp".' },
  '演员|0': { prompt: 'Chính vì ông vốn là diễn viên Kinh kịch nổi tiếng thời trẻ, nên rất được khán giả yêu mến.',
    answer: '正因为他本来就是年轻时很有名的京剧演员，所以深受观众的喜爱。', pair: '因为……所以……',
    note: '本来 là từ bài 4; 深受……喜爱 — được yêu thích sâu sắc.' },
  '观众|0': { prompt: 'Buổi diễn lần này không những tổ chức rất thành công, mà còn thu hút không ít khán giả địa phương.',
    answer: '这次演出不但举办得非常成功，而且还吸引了不少当地的观众。', pair: '不但……而且……',
    note: '举办 là từ bài 6, 成功 là từ bài 4.' },
  '观众|1': { prompt: 'Kinh kịch cũng đang thay đổi, để bất kể khán giả ở độ tuổi nào cũng thấy thích xem.',
    answer: '京剧也在改变，为了让不管什么年龄的观众都爱看。', pair: '不管……都……',
    note: '改变 là từ bài 3, 年龄 là từ bài 5.' },
  '演出|0': { prompt: 'Ông lên sân khấu từ năm 8 tuổi, tính đến nay chắc đã hát hơn 60 năm.',
    answer: '他8岁就开始上台演出，到现在大概唱了60多年了。', pair: '大概……',
    note: '大概 + số lượng — ước chừng bao nhiêu.' },
  '演出|1': { prompt: 'Hồi nhỏ tôi không những hay đi xem ông diễn, mà ông còn kể cho tôi nhiều chuyện lịch sử.',
    answer: '我小时候不但经常去看他的演出，而且他还给我讲很多历史故事。', pair: '不但……而且……',
    note: '一场演出 — 演出 làm danh từ thì dùng lượng từ 场.' },
  '大概|0': { prompt: 'Kế hoạch tổ chức lễ hội văn hoá này, chỉ cần viết rõ ràng thì hiệu trưởng có lẽ sẽ đồng ý.',
    answer: '这个举办文化节活动的计划，只要写得清楚，校长大概就会同意。', pair: '只要……就……',
    note: '计划 là từ bài 4, 活动 là từ bài 6.' },
  '大概|1': { prompt: 'Không cần sắp xếp quá chi tiết, nhưng nhất định phải có một ý tưởng đại khái.',
    answer: '虽然不用安排得特别详细，但是必须有一个大概的想法。', pair: '虽然……但是……',
    note: '安排 là từ bài 3, 详细 là từ bài 12.' },
  '来自|0': { prompt: 'Tôi cứ tưởng du học sinh đến từ Mỹ thì khó hát Kinh kịch, ai ngờ cậu ấy hát hay đến vậy.',
    answer: '我以为一个来自美国的留学生很难唱好京剧，没想到他唱得这么好。', pair: '以为……没想到……',
    note: '来自 đã gồm nghĩa "từ": ✗ 来自从美国.' },
  '来自|1': { prompt: 'Lễ hội văn hoá không những giúp sinh viên các nước hiểu Trung Quốc hơn, mà còn giúp họ kết bạn.',
    answer: '文化节活动不但能让来自各国的学生更好地了解中国，而且还能让他们交到朋友。', pair: '不但……而且……',
    note: '各 là từ bài 6, 交朋友 là từ bài 2.' },
  '遍|1': { prompt: 'Tôi thường học hát theo tivi rồi luyện đi luyện lại, thỉnh thoảng còn hát vài câu cùng người Trung Quốc.',
    answer: '我常常跟着电视学唱，然后一遍一遍地练习，偶尔还跟中国人一起唱上几句。', pair: '先……然后……',
    note: '遍 nhấn trọn vẹn từ đầu đến cuối, khác 次 chỉ đếm lần.' },
  '吃惊|0': { prompt: 'Cậu ấy chẳng những biết hát Kinh kịch, mà còn hát hay, thật khiến người ta kinh ngạc.',
    answer: '他不但会唱京剧，而且唱得很好，真让人吃惊。', pair: '不但……而且……',
    note: '吃惊 là từ ly hợp: 吃了一惊, 大吃一惊.' },
  '基础|0': { prompt: 'Bạn học nhanh thật! — Vì hồi nhỏ tôi học hai năm múa nên có chút nền tảng.',
    answer: '你学得可真快！——因为我小时候学过两年的舞，所以有点儿基础。', pair: '因为……所以……',
    note: '打好基础 / 有基础 — kết hợp cố định.' },
  '正常|0': { prompt: 'Mới đến một môi trường mới mà thấy chưa quen thì rất bình thường, cứ từ từ sẽ thích nghi thôi.',
    answer: '刚到一个新环境，觉得不习惯是很正常的，只要慢慢来，就会适应的。', pair: '只要……就……',
    note: '适应 là từ bài 2 — thích nghi với hoàn cảnh mới.' },
  '申请|0': { prompt: 'Nghe nói bạn định xin đi du học, chuẩn bị tới đâu rồi? — Đang tiến hành, hồ sơ sắp xong.',
    answer: '听说你要申请去国外留学，准备得怎么样了？——正在进行，只要再等几天，材料就准备好了。', pair: '只要……就……',
    note: '材料 là từ bài 3; 进行 là từ bài này.' },
  '申请|1': { prompt: 'Chúng em muốn xin tổ chức lễ hội văn hoá, vì như vậy sinh viên các nước sẽ hiểu Trung Quốc hơn.',
    answer: '我们想申请举办文化节活动，因为这样各国学生就能更好地了解中国。', pair: '因为……',
    note: '申请 là xin phép cấp trên, khác 要求 (đòi hỏi).' },
  '有趣|0': { prompt: 'Chuyến dã ngoại lần trước các bạn tổ chức không những rất thú vị, mà ai cũng chơi rất vui.',
    answer: '上次的春游活动你们不但办得非常有趣，而且大家都玩儿得很开心。', pair: '不但……而且……',
    note: 'V + 得 + Adj — bổ ngữ trạng thái, dùng hai lần trong một câu.' },
  '开心|0': { prompt: 'Cứ thấy bọn trẻ cười vui là bố mẹ cũng thấy hạnh phúc.',
    answer: '一看到孩子们开心地笑，父母就觉得很幸福。', pair: '一……就……',
    note: '幸福 là từ bài 1; 开心 thiên khẩu ngữ hơn 愉快 (bài 8).' },
  '开心|1': { prompt: 'Vì hoạt động lần này tiếp tục do bạn phụ trách, nên tôi tin chắc sẽ rất thành công.',
    answer: '因为这次活动继续由你负责，所以我相信一定会很成功。', pair: '因为……所以……',
    note: '由 + ai + 负责 — do ai phụ trách; 负责 là từ bài 3.' },
  '由|1': { prompt: 'Việc này chẳng phải giám đốc Mã phụ trách sao? — Anh ấy rời công ty rồi, nên giờ do giám đốc Vương phụ trách.',
    answer: '这件事不是马经理专门负责吗？——因为他已经离开公司了，所以现在由王经理负责。', pair: '因为……所以……',
    note: '由 nêu người LÀM; 被 nêu người CHỊU tác động.' },
  '讨论|0': { prompt: 'Chúng tôi về sẽ họp bàn ngay, chỉ cần trước thứ Sáu là gửi bản kế hoạch chi tiết cho ngài.',
    answer: '我们回去就开会讨论，只要在星期五之前，就把详细的计划书发给您。', pair: '只要……就……',
    note: '详细 là từ bài 12; 讨论 chính thức hơn 商量.' },
  '大约|0': { prompt: 'Đũa ở Trung Quốc không những đã có lịch sử khoảng hơn 3000 năm, mà đến nay vẫn được dùng hằng ngày.',
    answer: '筷子在中国不但大约已经有3000多年的历史了，而且到现在还每天都在用。', pair: '不但……而且……',
    note: '大约 chỉ dùng cho SỐ LƯỢNG, khác 大概 còn để phỏng đoán.' },
  '餐厅|1': { prompt: 'Một số nhà hàng Trung Quốc ở nước ngoài còn cung cấp hướng dẫn chi tiết cách dùng đũa, vì nhiều khách không biết dùng.',
    answer: '国外的一些中国餐厅还会提供使用筷子的详细说明，因为很多客人不会用。', pair: '因为……',
    note: '提供 là từ bài 3, 使用 và 说明 là từ bài 12 và bài 7.' },
  '纸袋|1': { prompt: 'Nếu bạn rảnh thì cho những thứ này vào túi giấy giúp mình nhé.',
    answer: '要是你有空，就把这些东西放进纸袋里吧。', pair: '要是……就……',
    note: 'Câu chữ 把: 把 + tân ngữ + 放进 + nơi chốn + 里.' },
  '互联网|1': { prompt: 'Nhờ Internet, chúng ta không những tìm được thông tin rất nhanh, mà còn giao lưu được với người khắp nơi.',
    answer: '通过互联网，我们不但可以很快地找到需要的信息，而且还能跟各地的人交流。', pair: '不但……而且……',
    note: '通过 là từ bài 9, 交流 là từ bài 2.' },
  '进行|0': { prompt: 'Sáu giờ rồi mà sao cuộc họp chưa xong? — Vẫn đang tiến hành, có lẽ còn nửa tiếng nữa.',
    answer: '都六点了，会议怎么还没结束？——还在进行，大概还要半个小时。', pair: '大概……',
    note: 'Sau 进行 phải là danh từ song âm: 进行调查 ✓ / 进行吃 ✗.' },
  '进行|1': { prompt: 'Người học ngôn ngữ thành công không những chủ động trao đổi với người khác, mà còn nhờ người ta sửa lỗi cho mình.',
    answer: '成功的语言学习者不但会主动与他人进行交流，并且还请别人帮助他们改错。', pair: '不但……并且……',
    note: '语言 là từ bài 12, 与 là từ bài 3.' },
  '错误|0': { prompt: 'Ai cũng có thể mắc sai lầm, mấu chốt không phải là không sai, mà là sửa kịp thời.',
    answer: '人人都会犯错误，关键不是不犯错，而是要及时改正。', pair: '不是……而是……',
    note: '关键 là từ bài 10, 及时 là từ bài 2.' },
  '随着|0': { prompt: 'Cùng với sự phát triển của xã hội, tiêu chuẩn cái đẹp luôn đổi: xưa lấy béo làm đẹp, nay lại lấy gầy làm đẹp.',
    answer: '随着社会的发展，美的标准一直在变：过去人们以胖为美，而现在的人以瘦为美。', pair: '……，而……',
    note: '标准 là từ bài 5, 发展 là từ bài 10; 随着 dẫn quá trình, không dẫn người.' },
  '十分|0': { prompt: 'Đối với kế hoạch khảo sát lần này, giám đốc không những vô cùng hài lòng, mà còn khen cả nhóm.',
    answer: '对于这次调查计划，经理不但十分满意，而且还表扬了整个小组。', pair: '不但……而且……',
    note: '对于 là từ bài 12, 调查 là từ bài 4.' },
  '十分|1': { prompt: 'Chỉ cần tạo được thói quen đọc sách là việc học sẽ tiến bộ, cho nên điều đó vô cùng quan trọng.',
    answer: '只要养成阅读的习惯，学习就会有进步，所以这一点十分重要。', pair: '只要……就……',
    note: '养成 và 阅读 đều là từ bài 11.' },
  '普遍|1': { prompt: 'Dùng điện thoại thanh toán ở Trung Quốc không những đã rất phổ biến, mà còn ngày càng tiện lợi.',
    answer: '用手机付钱在中国不但已经非常普遍了，而且越来越方便。', pair: '不但……而且……',
    note: '付款 là từ bài 5 — 用手机付钱.' },
  '部分|1': { prompt: 'Bài viết này giới thiệu Kinh kịch: phần đầu do tôi viết, còn phần hai do bạn tôi viết.',
    answer: '这篇文章是介绍京剧的，前一部分由我写，而第二部分由我朋友写。', pair: '……，而……',
    note: '篇 và 文章 đều là từ bài 11; 由 + ai + V.' },
  '稍微|0': { prompt: 'Mọi người về phòng nghỉ một chút đã, nửa tiếng sau thì tập trung dưới sảnh.',
    answer: '大家先回房间稍微休息一下，然后半个小时后我们楼下集合。', pair: '先……然后……',
    note: '稍微 bắt buộc có 一下 / 一点儿 theo sau.' },
  '稍微|1': { prompt: 'Câu này tuy hơi khó một chút, nhưng chỉ cần nghĩ kỹ là bạn làm được.',
    answer: '这道题虽然稍微有点儿难，但是只要仔细想想，你就能做出来。', pair: '虽然……但是……',
    note: '仔细 là từ bài 12; V + 出来 — nghĩ ra, làm ra.' },
  '苦|1': { prompt: 'Loại cà phê này nếu không thêm đường thì hơi đắng, nên tôi luôn cho một thìa.',
    answer: '这种咖啡要是不加糖的话就有点儿苦，所以我总是加一勺。', pair: '要是……就……',
    note: '糖 là từ bài 10, 勺 là từ bài 12.' },
  '省|0': { prompt: 'Trung Quốc không những có rất nhiều tỉnh, mà mỗi tỉnh đều có đặc điểm riêng.',
    answer: '中国不但有很多省，而且每个省都有自己的特点。', pair: '不但……而且……',
    note: '特点 là từ bài 8 — 共同特点 / 自己的特点.' },
  '省|1': { prompt: 'Anh ấy đến từ tỉnh Vân Nam, chính vì vậy mà rất hiểu về trà.',
    answer: '他来自云南省，正因为这样，所以他对茶特别了解。', pair: '因为……所以……',
    note: '来自 + nơi chốn — không thêm 从.' }
};
